### ISSUE TITLE
cpu/ram usage requirements and limits

### ISSUE THREAD

**Issue by gkiar** [boutiques/boutiques#102]
I am wondering what the suggested way to encode CPU and RAM minimum requirements and hard limits is within Boutiques. My current best guess is using the `"custom"` key like is done [here](https://github.com/boutiques/boutiques/blob/master/examples/custom-properties/custom.json#L25), but am not sure if I overlooked these fields as an existing part of the schema. I recall there does exist a `"walltime-estimate"` field, so perhaps these requirements or limits could be optional fields, as well, eventually.

My usecase is that I would like to be able to submit jobs through Boutiques to the cloud directly, and when creating job definitions you need to specify core and memory requirements so the appropriate number and type of nodes are launched for your queue.

Thanks!

**Comment by kofalt** [comment]
Related: #63 :slightly_smiling_face:

**Comment by glatard** [comment]
I'd say use a custom field for now and when you tested that we could add it to a next version of the spec.

**Comment by gkiar** [comment]
great - thanks!
