### ISSUE TITLE
Update nipype2boutiques script to support 0.5

### ISSUE THREAD

**Issue by gkiar** [boutiques/boutiques#135]

**Comment by erinb90** [comment]
Hi @gkiar, I'll be working on this. Anything useful I should know before I start?

**Comment by gkiar** [comment]
Hey @erinb90 - thanks for checking in.

The big catch here is that Nipype doesn't have a standard way of representing outputs for its nodes. Sometimes they are set to hard coded values, or determined as soon as inputs are provided, or produced only at runtime, and in each of these cases there isn't a common method for extracting the "recipe" they will be following. My suggestion would be to pick a handful of the example interfaces in the nipype repository and build solutions for them directly, and see where you can generalize.

And remember: perfect is the enemy of good :) We _might_ not be able to support all nipype interfaces.

**Comment by erinb90** [comment]
Thanks @gkiar! 

Do you have any example usages of the `nipype2boutiques` script I can look at to get started? I'm completely new to Nipype and am trying to understand what parameters I need to pass to it, and what dependencies I need for it to work. I have the Nipype repo cloned and installed already.

**Comment by gkiar** [comment]
I don't, unfortunately - I've played with it a bit, but spent more time thinking about how to solve arbitrarily defined outputs than building a minimum working example :'( 

I'd probably recommend installing and developing this inside a Docker/singularity container with `fsl` installed, since `bet` is a very common, easy, and quick-to-run tool. You can find a container and descriptor for it on Zenodo through `bosh search`. For data, you just need 1 MRI image as input. I can send you one if you don't have one handy, but you can also look in the Travis config on Clowdr for downloading one [here](https://github.com/clowdr/clowdr/blob/master/.travis.yml#L41). Happy to sit down and clarify things a bit more if that would help!

@ValHayot knows Nipype pretty well, and might be a good resources for you if you have questions about it, too!

**Comment by ValHayot** [comment]
Hey @erinb90, I only ran `nipype2boutiques` once (albeit recently) but unfortunately do not recall much of it. Don't know how helpful this will be for you, but if you need an intro to Nipype interfaces and how they work, you can check this out https://github.com/miykael/nipype_tutorial/blob/master/notebooks/advanced_create_interfaces.ipynb and you can check this out for a list of their interfaces and how they work https://nipype.readthedocs.io/en/latest/documentation.html.
I'll check if I have my example saved somewhere though!

**Comment by erinb90** [comment]
After some investigation, I don't think it will be possible to create a script that will produce a *perfect* descriptor for every interface, but I think I can I make it produce a nearly perfect one for most cases. And then I guess we would have to manually edit the parts that are wrong before publishing it, which isn't too bad. Still much faster than writing the descriptor from scratch. I will keep working on it and see what I can do.

**Comment by glatard** [comment]
Sounds very good. Perhaps you could list here what's your planned list of descriptors to work on, and we could re-order as we see fit?

**Comment by erinb90** [comment]
Sure. Are there any particular Nipype interfaces we want to prioritize? Or should I just pick any of them?

Another thing I noticed is that Nipype supports compound input types. For example I saw one input that could either be a file or a boolean (if you give a file it will use that file, and if you give it True it will instead use the file from another input). How would we deal with this in Boutiques?

**Comment by glatard** [comment]
I'm not sure of what's in there exactly, but we should start from the most popular toolboxes. That includes FSL, AFNI, MRTrix, Dipy, ... 

I don't think there's a general answer to compound input types. In the example you mention, I would create two separate inputs, with different types, and adjust input dependencies accordingly (make them mutually exclusive, and have the boolean one require the second file).

**Comment by erinb90** [comment]
I'm noticing a lot of cases where the output path templates are only provided under certain input conditions. So to get the path templates we would probably need to run the interface with every possible input combination, which seems like overkill. For now I just put some placeholder text for the path template when it's undefined, warning the user that they need to manually provide it.

**Comment by gkiar** [comment]
Ya @erinb90 - I arrived at the same conclusion, and think in general it seems that tools' outputs are under-defined until magically appear at the end of execution. Your plan sounds good. Another option could just be putting a wildcard as the path template, so once we fix #397 this will at least be able to be run, and then back-populated

**Comment by glatard** [comment]
Another way is to use an output directory, and to dump all the output files in there. At least that could provide a first cut that works.
