### ISSUE TITLE
add bosh-batch function

### ISSUE THREAD

**Issue by gkiar** [boutiques/boutiques#149]
I have:
- a dataset that is organized according to some standard
- a descriptor with its corresponding invocation schema, and
- a mapping (in a `json` file) from inputs (represented by regular expressions of the input dataset)

`bosh-batch` will apply the regex to the dataset and generate invocations for all reasonable sets of inputs and save them.

p.s. I will be needing this for `clowdr`.

**Comment by glatard** [comment]
should this be part of `bosh-invocation`?

**Comment by gkiar** [comment]
@glatard - based on subsequent discussions, I believe this just is clowdr. Close if you agree
