### ISSUE TITLE
API: execute should capture and return stdout, stderr and tool exit code

### ISSUE THREAD

**Issue by glatard** [boutiques/boutiques#162]

**Comment by glatard** [comment]
Once done, use this feature in `sim`.

**Comment by gkiar** [comment]
Regarding exit code: we should be sure to leverage [these Docker exit codes](https://docs.docker.com/engine/reference/run/#exit-status) to help give us provide more useful errors to users.

Regarding stdout/err: we should use `docker logs` and `--log-driver` for this, as [documented here](https://docs.docker.com/engine/reference/run/#logging-drivers-log-driver). I suspect we want the default (`json-file`). One limitation here is that they put `stdout` and `stderr` together, which isn't great. I'm looking into using the Docker engine API for querying them independently.

**Comment by gkiar** [comment]
Ok, tested out `dockerpy` which wraps Docker's RESTful API. The command I ran was:

```
import docker
client = docker.from_env()

cid  = 'mycontainerid'
container = client.containers.get(cid)
print("Standard Out:")
print(container.logs(stdout=True, stderr=False))
print("Standard Error:")
print(container.logs(stdout=False, stderr=True))
```

The output: 

```
Standard Out:
root@4a4e60e1f999:/# echo "thingy"
thingy
root@4a4e60e1f999:/# echasdfasdf
bash: echasdfasdf: command not found
root@4a4e60e1f999:/# exit
exit

Standard Error:

```

From the above, it looks like (despite there being an obvious error in the text), all outputs are logged to standard out within Docker for some reason. @glatard, do you have any insight?

**Comment by glatard** [comment]
I don't mind of stderr and stdout are merged (for now). We can definitely leverage the Docker exit codes. But currently bosh exec would raise an exception if the exit code was not 0 and not return any log. We need to have bosh exec return (code, log) and let the clients handle errors and present logs as they wish.

**Comment by shots47s** [comment]
Something I did in my current code was to pip the command to an output in the "command-line" of the boutiques descriptor which allowed me to capture explicitly the stdout and stderr fo the command.  Something like this to a temp file that is served back to the user in the working directory might work for this.

**Comment by glatard** [comment]
It's always possible to do that but I think bosh should capture it and print it to its own stdout/err by default.

**Comment by shots47s** [comment]
Ok, I see the distinction.

**Comment by glatard** [comment]
Error messages could be printed based on the exit code, now that tools can document error messages (see https://github.com/boutiques/boutiques/pull/196)
