### ISSUE TITLE
add CI and testing for Python2.6 (currently it crashes?)

### ISSUE THREAD

**Issue by gkiar** [boutiques/boutiques#166]

**Comment by glatard** [comment]
Supporting Python 2.6 might not be a piece of cake: to start with, `jsonschema` doesn't  support Python 2.6. @camarasu, I think this originated on your Python 2.6 requirement on EGI worker nodes; would it still help if Boutiques was supporting 2.6 or is it now outdated?

**Comment by glatard** [comment]
okay @camarasu, Boutiques now supports Python 2.6, there is no remaining excuse for not using `bosh` in VIP :)
