### ISSUE TITLE
Problems with pip upgrade and bosh installation on CentOS6

### ISSUE THREAD

**Issue by pascalgirard** [boutiques/boutiques#167]
Please find in attached file informations on CentOS release and python version on moteur1 server. Then a list of steps I followed to install boutiques tools, with errors. Theses steps work well on newk server which characteristics are : 
- CentOS Linux release 7.3.1611 (Core)
- Python 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux2

 
[boutique_tools_installation_and_problems.txt](https://github.com/boutiques/boutiques/files/1359861/boutique_tools_installation_and_problems.txt)

**Comment by gkiar** [comment]
@pascalgirard thanks for this. Based on the outputs, you're using Python2.6 on CentOS, which does not support dictionary comprehension (a feature used within Boutiques). Could you please follow the [following guide](https://gist.github.com/xuelangZF/570caf66cd1f204f98905e35336c9fc0) to install Python2.7 on your system, and then try installing and using Boutiques?

Thanks

**Comment by glatard** [comment]
Closing this as we won't support Python 2.6 any time soon.
