### ISSUE TITLE
Publish more applications to Zenodo

### ISSUE THREAD

**Issue by glatard** [boutiques/boutiques#174]
@camarasu, @pascalgirard: when VIP supports version 0.5 of the schema, you could use `bosh publish` to publish as many VIP applications as possible to neurolinks.

**Comment by glatard** [comment]
We should also publish existing descriptors written by @natacha-beck, @shawntbrown, @gkiar and others.

**Comment by glatard** [comment]
List of descriptors to be published:
* ndmg: 
* [ICA-AROMA](https://github.com/aces/cbrain-plugins-neuro/blob/master/cbrain_task_descriptors/ICA-AROMA.json)
* [FSL-ProbtackX](https://github.com/aces/cbrain-plugins-neuro/blob/master/cbrain_task_descriptors/fsl_probtrackx2.json)

These ones have no container image, they should be tested with the FSL images from [FSL-ProbtackX](https://github.com/aces/cbrain-plugins-neuro/blob/master/cbrain_task_descriptors/fsl_probtrackx2.json):
* [FSL Bet](https://github.com/aces/cbrain-plugins-neuro/blob/master/cbrain_task_descriptors/fsl_bet.json)
* [FSL Fast](https://github.com/aces/cbrain-plugins-neuro/blob/master/cbrain_task_descriptors/fsl_fast.json)
* [FSL First](https://github.com/aces/cbrain-plugins-neuro/blob/master/cbrain_task_descriptors/fsl_first.json)

It would also be nice to add basic tags, for instance: 'domain=neuroinformatics'.

**Comment by erinb90** [comment]
@glatard For the last 3 descriptors, what do you mean by "they should be tested with the FSL images from FSL-ProbtackX"? Do I need to add the `container-image` and then launch an invocation?

**Comment by glatard** [comment]
yes, that's it.

**Comment by erinb90** [comment]
@glatard Where do I get the required inputs for the invocation?

**Comment by glatard** [comment]
You can take the following image:
```ds001/sub-01/anat/sub-01_T1w.nii.gz``` from the archive in ```https://drive.google.com/drive/u/0/folders/0B2JWN60ZLkgkMGlUY3B4MXZIZW8```. Use the default parameters for bet, fast and first. And consider adding this image to the container and add a `test` to the descriptor, so that others don't fall in the same problem.

**Comment by erinb90** [comment]
> You can take the following image:
> `ds001/sub-01/anat/sub-01_T1w.nii.gz` from the `ds001.tar` archive in `https://drive.google.com/drive/u/0/folders/0B2JWN60ZLkgkMGlUY3B4MXZIZW8`. Use the default parameters for bet, fast and first. And consider adding this image to the container and add a `test` to the descriptor, so that others don't fall in the same problem.

@glatard `fsl_fast` and `fsl_first` both take a very long time to execute in the container and I haven't had the chance to let either of them complete. But with verbose output enabled, I can see that they are running and doing things. Is this enough to conclude that the descriptors are good or should I leave them running until they finish?

**Comment by glatard** [comment]
It's always a good idea to run them to the end. They shouldn't take more than a few minutes though, as far as I remember.

**Comment by gkiar** [comment]
@erinb90 the case when they'd take longer, in my experience, is if they're RAM starved. Try giving them a bit more RAM, and @glatard's estimate should be about right.

**Comment by erinb90** [comment]
It was definitely a RAM issue, because when I ran them on the lab computer (instead of my 4 GB RAM VM) they finished quickly. 

Another question: `fsl_fast` and `fsl_first` both return a directory (not a gz file) as their output. If I want to write tests for them, how can I verify the MD5 checksum of a directory? I googled it and it seems possible but complicated.

**Comment by glatard** [comment]
I don't think we want to compute the checksum of a directory. If you post the list of files in the directory, I could tell which ones could be used as reference.

**Comment by erinb90** [comment]
@glatard These are the files for fsl_fast:
![screenshot from 2018-10-25 15-22-28](https://user-images.githubusercontent.com/14361988/47526210-129b4280-d86d-11e8-85ab-4a47926a28b6.png)

and the files for fsl_first:
![screenshot from 2018-10-25 15-41-31](https://user-images.githubusercontent.com/14361988/47526221-19c25080-d86d-11e8-81d1-7be6f13937b2.png)

**Comment by glatard** [comment]
You can test on `img_fast_seg.nii.gz` and `_all_fast_firstseg.nii.gz`.

**Comment by erinb90** [comment]
@glatard I still haven't figured out how to test `fsl_first` and `fsl_fast` given only the output directory ID, any ideas?

**Comment by glatard** [comment]
OK, I understand now. In that case I think you could just specify that the output directory must exist, it should work if you don't specify the checksum in the test.

**Comment by erinb90** [comment]
I finally finished publishing these 😁

**Comment by glatard** [comment]
Great work @erinb90, thanks!
