### ISSUE TITLE
Installing boutiques python tools from easy_install places files in the incorrect directory within the python site-packages

### ISSUE THREAD

**Issue by shots47s** [boutiques/boutiques#180]
Discovered this while using the `python setup.py install` as an easy way to test changes to my fork. 

setup.py puts files in the egg directory directly, but everything else is looking for files under egg/boutiques.  If one runs bosh-validate <schema> then you get the error:

`
PATH = /usr/local/lib/python2.7/dist-packages/boutiques-0.5.3-py2.7.egg/boutiques fil = __init__.pyc
Traceback (most recent call last):
  File "/usr/local/bin/bosh-validate", line 9, in <module>
    load_entry_point('boutiques==0.5.3', 'console_scripts', 'bosh-validate')()
  File "/usr/local/lib/python2.7/dist-packages/boutiques-0.5.3-py2.7.egg/boutiques/validator.py", line 247, in main
    descriptor = validate_json(results.jsonfile)
  File "/usr/local/lib/python2.7/dist-packages/boutiques-0.5.3-py2.7.egg/boutiques/validator.py", line 44, in validate_json
    with open(schema_file) as fhandle:
IOError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/boutiques-0.5.3-py2.7.egg/boutiques/schema/descriptor.schema.json'
`

Suggesting altering the __init__.py to search for it under the correct path.

**Comment by gkiar** [comment]
Hey Shawn,

Have you tried this with the up to date cli? The documentation for it is on
the dev branch readme. I'm wondering if this could just be a lingering
issue from an old interface. The new command would be `bosh validate
descriptor.json`.

**Comment by shots47s** [comment]
I am in the master branch, and I get the same behavior regardless of using bosh validate or bosh-validate.  I will switch to dev branch.

**Comment by glatard** [comment]
Is this still a problem with the new cli?

**Comment by shots47s** [comment]
I just tested and it seems now to work fine.
