### ISSUE TITLE
broken links in `Getting Started with Boutiques.ipynb`

### ISSUE THREAD

**Issue by kaczmarj** [boutiques/boutiques#183]
Hello,

I was following [`Getting Started with Boutiques.ipynb`](https://github.com/boutiques/boutiques/blob/master/examples/Getting%20Started%20with%20Boutiques.ipynb) and noticed several links lead to 404s. Otherwise, the notebook is great!

Thanks,
Jakub

**Comment by gkiar** [comment]
Thanks, @kaczmarj ! I'll get on that :)
