### ISSUE TITLE
Several docker volumes with bosh

### ISSUE THREAD

**Issue by pascalgirard** [boutiques/boutiques#189]
Is it possible to give to bosh several docker volumes to share with the docker container ? For example in VIP we can have : "docker run --rm -v $PWD:/gasw-execution-dir -v $PWD/../cache:$PWD/../cache docker/image:3.0 ..."

**Comment by glatard** [comment]
`bosh exec launch -v $PWD:/gasw-execution-dir $PWD/../cache:$PWD/../cache` should work

**Comment by glatard** [comment]
Please re-open if it doesn't.
