### ISSUE TITLE
Very cryptic error message provided when input.json has input parameters not in line with boutiques descriptor.

### ISSUE THREAD

**Issue by shots47s** [boutiques/boutiques#193]
We should add some error handling that provides the users with more relavant information for debugging as now if you have something in the input.json that is not in line with the boutiques descriptor, the error that is sent back looks like this:

File "python3.5/site-packages/boutiques-0.5.4-py3.5.egg/boutiques/localExec.py", line 39, in <lambda>
    self.byId       = lambda n: [ v for v in self.inputs+self.outputs if v['id']==n][0]
IndexError: list index out of range

Which is not very helpful.  

Propose to have a input file validation method be created that checks this and fails with meaningful error messages.

**Comment by gkiar** [comment]
Thanks, @shots47s! I agree, that would be better :)
