### ISSUE TITLE
Support for Vagrant Images

### ISSUE THREAD

**Issue by shots47s** [boutiques/boutiques#195]
Looking at the logic for Singularity and Docker images, it should be straight forward to support Vagrant images as well and provide our users one more possibility for launching images through boutiques.  Technically, this would be virtual machine support rather than container support, but from here there is no reason that Boutiques could not pull virtual machines from various repos and use them to execute pipelines.  Seems little effort to provide a new capability that is popular amongst a group of folks.

**Comment by shots47s** [comment]
From Boutiques meeting on 1.11.18:

Reasons why:
1. Provides another option for Boutiques users.
2. May be more secure in an HPC environment than docker.
3. A good methodology for expressing more complex workflows as an alternative to Docker-compose.  

Reasons Why Not:
1. Not a compatible technology to singularity and docker, so conversion between Vagrant and the others is not possible (Shawn will explore).
2. Much heavier than container technology (i.e. start up is significant)

**Comment by kofalt** [comment]
If support for the same image across all executors is important, you could have a standard image that boots a docker daemon inside it and runs the image. A little silly, but it'd get out-of-the-box running on any platform...

**Comment by glatard** [comment]
From the May 3rd meeting: we don't really want to support VMs in Boutiques for now as it opens a whole range of new questions and the use case is not so clear. So we would lean towards not supporting Vagrant. @shots47s, what do you think?

**Comment by shots47s** [comment]
It was only offered as a suggestion, if there is no clear use case to support VMs then I would agree.  Thanks for considering it.

Shawn

-- 
Shawn T. Brown, PhD.
Associate Director of Research Software Development  / CBRAIN Platform
McGill Centre for Integrative Neuroscience (MCIN)
McGill University
Montreal, QC, Canada
Email: stbrown@mcin.ca
Phone: 514-237-2960

**Comment by glatard** [comment]
Then let's close this for now and reopen if/when needed.
