### ISSUE TITLE
Support for tools without a container image

### ISSUE THREAD

**Issue by glatard** [boutiques/boutiques#198]
The spec allows for the definition of tools that don't have a container image. This is useful in case tools are pre-installed on the infrastructure (e.g. a cluster) or only simple shell utilities are used (e.g. for testing). We should make sure that `bosh` supports such tools and that this feature is covered by tests. 

User feedback (GigaScience reviewer):

I installed Boutiques version 0.5.3 (Python 3.6.3 on OS X 10.11.6) to test the minimal Boutiques descriptor in Listing 5. This descriptor passed the validation step, but when attempting to conduct a simulation run of the descriptor given an input JSON file with the contents `{"param": 5}`, a `KeyError` was produced, indicating that the key "container-image" was not present in the descriptor. This led me to wonder whether "container-image" is a required field in the descriptor schema and whether `bosh` can execute on bare metal.

**Comment by gkiar** [comment]
This is now implemented in my branch - I will close this when we merge. The functionality existed, but the bug was in using `[]` access vs `.get()` access for dictionary properties (Ruby returns `None` in the former context, whereas Python throws an exception).
