### ISSUE TITLE
`bosh` exec should validate the descriptor before trying to run it

### ISSUE THREAD

**Issue by glatard** [boutiques/boutiques#199]
User feedback (GigaScience reviewer):

When trying to run the example in https://github.com/boutiques/boutiques/tree/https://github.com/boutiques/boutiques/tree/5678d6f84bc1863741c6b8c595f037f622936c5c/tools/python/boutiques/schema/examples/example1/tools/python/boutiques/schema/examples/example1, validation of the invocation and descriptor functioned as described. For instance, validation failed when `enum_input` and `num_input`, mutually exclusive parameters, were both specified. Validation did not fail, however, when attempting to run a 'simulation' or 'launch' with the same invalid inputs. The authors should consider including the validation step when running the program with `bosh exec`.

**Comment by gkiar** [comment]
Just addressed in a commit on my fork. Will close when we merge
