### ISSUE TITLE
API should support passing descriptors and invocations as JSON objects instead of files

### ISSUE THREAD

**Issue by glatard** [boutiques/boutiques#213]
It feels like `bosh` should accept JSON objects read from the main method.

**Comment by gkiar** [comment]
Agreed!

**Comment by erinb90** [comment]
Is this a duplicate of #277?

**Comment by glatard** [comment]
Related but not duplication: #277 is about the CLI, this is for the API. Does your PR address both?

**Comment by erinb90** [comment]
@glatard Yes, with my changes we are able to pass JSON objects either by the CLI or using the API.
