### ISSUE TITLE
Use local Singularity image first

### ISSUE THREAD

**Issue by glatard** [boutiques/boutiques#231]
Currently, bosh tries to pull the SIngularity image first, and it falls back on the local image if pull fails. This is annoying when the local image is already here since pull takes a lot of time. We should pull only when no local image is available.

**Comment by gkiar** [comment]
Actually, we do that already (see [here](https://github.com/boutiques/boutiques/blob/develop/tools/python/boutiques/localExec.py#L97)). The catch is that depending where you pull your singularity image from, the name will be different, so we must pull it with a `--name` option originally.

I imposed the convention that the name `org/repo` will pull to `org-repo.simg` in the current directory. If it is not named like this, Boutiques won't find it. Perhaps we should update it so `org/repo:tag` goes to `org-repo-tag.simg`, and we automatically add `latest`, whereas currently it'd go to `org-repo:tag.simg`, which is a bit funny for a filename.

**Comment by glatard** [comment]
Then how about we just add a debug message that says "Looking for image xxx locally" so that we can understand why it's not found?

**Comment by gkiar** [comment]
I support that
