### ISSUE TITLE
bosh search

### ISSUE THREAD

**Issue by glatard** [boutiques/boutiques#241]
`bosh search` will search for boutiques descriptors on Zenodo. Descriptors will be retrieved from the `boutiques` keyword and possibly other keywords such as `schema-version` or `container-image`. This should be implemented using the Records search API, currently in testing (see http://developers.zenodo.org/#rest-api).

Easy extensions to `search` could include `pull` and run from descriptor, following the Docker client model.

**Comment by glatard** [comment]
`bosh search` should behave as `docker search`. We could use the Zenodo ID as key in the returned list. Then, keys should be usable in other commands, such as `bosh exec`, etc.

**Comment by glatard** [comment]
The Zenodo query to get Boutiques descriptors should be:
q=boutiques&keywords=boutiques&keywords=schema&keywords=version&file_type=json&type=software

Hopefully the Records API allows for that. If not, let's hack something from the URL.

**Comment by erinb90** [comment]
This issue can be closed.
