### ISSUE TITLE
Duplication problem in the schema

### ISSUE THREAD

**Issue by axlbonnet** [boutiques/boutiques#247]
There is duplication problem with "exclusive-minimum" and "exclusive-maximum" at this place (they're already defined just above) :

https://github.com/boutiques/boutiques/blob/5f1e5a2e6d0abb8e01749126f5cba35b195075f9/tools/python/boutiques/schema/descriptor.schema.json#L379-L380

I can't find if it is valid or not but it is obviously not a good practice, and I think most json parsers will fail or silently select one of the 2 elements. Anyway, I can't currently use the boutiques schema as an external reference in an OpenAPI document because of that.

**Comment by glatard** [comment]
Good catch! The solution to this problem is actually to remove the following:
```
"exclusive-minimum": {
                        "properties": {
                            "type": {"enum": ["Number"]}
                        }
}
```
Indeed, the dependency of `exclusive-minimum` to `Number` is implied by the dependency to `minimum`. 

This is fixed in #248.
