### ISSUE TITLE
Add support for JSON objects passed on the CLI in bosh

### ISSUE THREAD

**Issue by glatard** [boutiques/boutiques#277]
In a curl way, e.g., `bosh exec launch descriptor.json '{"image": "/path/image.nii.gz", "param": 1}'`

**Comment by glatard** [comment]
#213 implements that for `bosh exec launch`. The following functions of the CLI/Python API should also be modified:
- [ ] exec
- [ ] simulate
- [ ] import
- [ ] export
- [ ] publish
- [ ] invocation
- [ ] evaluate
- [ ] test

**Comment by glatard** [comment]
@erinb90, was this solved by #323?

**Comment by erinb90** [comment]
@glatard I think so, but I plan to write test cases for everything to confirm
