### ISSUE TITLE
Fix non-deterministic random-input failure

### ISSUE THREAD

**Issue by gkiar** [boutiques/boutiques#278]
As exemplified [here](https://travis-ci.org/boutiques/boutiques/jobs/404447731#L3206-L3381).

**Comment by glatard** [comment]
hey @gkiar, is this fixed in one of your latest PRs?

**Comment by gkiar** [comment]
Unsure :) @glatard, I tried to fix it, and haven't seen it since, but as it's non deterministic, I couldn't quite be sure

**Comment by glatard** [comment]
This has been fixed for a while.
