### ISSUE TITLE
Check if input value keys can be used in environment variable values

### ISSUE THREAD

**Issue by glatard** [boutiques/boutiques#286]
... if not, add it!

**Comment by gkiar** [comment]
I.e.

```
{
 ...
 "command-line": "mycommand VALUE1 VALUE2 VALUE3",
 ...
 "environment-variables":
  [
    {
     "name": "something",
     "value": "VALUE1"
    }
  ]
}
```

Where `VALUE1` is first checked against command-line flags, and then substituted if no match found. Correct?

**Comment by gkiar** [comment]
Note: we could (maybe more robustly?) look this up by ID rather than command-line key

**Comment by glatard** [comment]
Duplicate of #307
