### ISSUE TITLE
spaces vs tabs in bosh.py line 38

### ISSUE THREAD

**Issue by MontrealSergiy** [boutiques/boutiques#293]
python 3.5, vagrant on "kwilczynski/ubuntu-16.04-docker"

(```
venv) vagrant@ubuntu1604:~/mirtk_draw$ bosh -h
Traceback (most recent call last):
  File "/home/vagrant/mirtk_draw/venv/bin/bosh", line 7, in <module>
    from bosh.bosh import main
  File "/home/vagrant/mirtk_draw/venv/lib/python3.5/site-packages/bosh/bosh.py", line 38
    self.do_ls(line)
                   ^
TabError: inconsistent use of tabs and spaces in indentation
```

**Comment by gkiar** [comment]
Hi @MontrealSergiy - I don't believe this is our package.

You should install Boutiques with `pip install boutiques`, and import it with `import boutiques`, not `import bosh`. This should be clear from our `README`, but please let me know if this is not the case.
