### ISSUE TITLE
If descriptor specifies docker image, but only singularity is installed, run in singularity

### ISSUE THREAD

**Issue by gkiar** [boutiques/boutiques#298]
This is useful so that people don't need multiple descriptors for the same tool, depending on what platform they want to run it on.

This would also be necessary for tools like CBRAIN to adopt `bosh` as a runtime tool across any Boureaux

**Comment by glatard** [comment]
When Docker and Singularity are both installed, we should also have an option in `bosh` to always use one or the other. For instance `--force-singularity` and `--force-docker`.

**Comment by glatard** [comment]
So to summarize, the behavior could be:
* `--force-singularity`: tries to run Docker images with Singularity. Errors if Singularity is not installed.
* `--force-docker`: tries to run `docker://`-prefixed Singularity images with Docker. Errors if Docker is not installed or the image isn't on DockerHub.
* No option (current behavior): runs images of type Singularity with Singularity, errors if Singularity is not installed. Runs images of type Docker with Docker, errors if Docker is not installed.

What do you think @gkiar, @camarasu, @ValHayot ?

**Comment by gkiar** [comment]
I would like to replace the last sentence in the third option:
- if described in docker, and docker not installed, check first for singularity and try to run there, if that fails, error.

**Comment by glatard** [comment]
so in this case, if described in singularity and image name starts with `docker://` and singularity is not installed, try in Docker?

**Comment by gkiar** [comment]
@glatard - I think no. If it starts with `docker://`, it should be defined as a Docker image, and `bosh` handles the execution in Singularity if Docker is not found. This would mean that any image defined with type `singularity` and image index `docker://` should be re-written with type `docker` and index `docker.index.io`. 

I don't think we need to support the case of going from Singularity to Docker because Singularity images cannot be (readily) converted to Docker images. If the descriptors described in this way currently are not modified this won't break their execution in Singularity, but they won't be able to take advantage of the proposed new feature to support both within a single descriptor as they're defined in the "terminal" virtualization type.

**Comment by erinb90** [comment]
How do we deal with the `container-opts` property when using `--force-singularity` and `--force-docker`? Container options are specific to either Docker or Singularity, so the command will usually fail if you try to put Docker options when executing with Singularity and vice-versa. 

Should we throw an error if the user tries to use `--force-singularity` or `--force-docker` and there are `container-opts` defined?
