### ISSUE TITLE
inputs can only belong to one group

### ISSUE THREAD

**Issue by leej3** [boutiques/boutiques#304]
need to be able to belong to more

**Comment by gkiar** [comment]
@glatard  an example would be a tool that has two inputs which must be paired (`all-or-none`), but are mutually exclusive with another options (`mutually-exclusive`).

I'd like to specify this as follows, assuming ids `2` and `3` must be used together, and are mutually exclusive with id `1`.

```
"groups": [
  {
    "id": "group1",
    "name": "group 1 name",
    "members": ["id1", "id2"],
    "mutually-exclusive": true
  },
  {
    "id": "group2",
    "name": "group 2 name",
    "members": ["id2", "id3"],
    "all-or-none": true
  }
]
```

For web forms, if they store the invocation based on input ID behind the scenes in JS, every field of an input could fetch the value from that object from memory, if it exists, and populate it. This just means some inputs could show up in two places, separated by group, but their values would be linked. Thoughts, @glatard ?

**Comment by gkiar** [comment]
The above for displaying is not unlike what you suggested - I'm not worried about the complexity yet, since I haven't seen complex examples of this behaviour being necessary.

**Comment by glatard** [comment]
Makes a lot of sense! Shall we then just stop checking that an input belongs to a single group in the validator?

**Comment by gkiar** [comment]
I think we'll need to replace it with logic ensuring an input doesn't belong to conflicting groups, but some of that should already be baked in elsewhere and can be adopted (i.e. no mutually exclusive groups with required inputs)

**Comment by erinb90** [comment]
So I thought of a couple rules we could implement once we start allowing inputs in multiple groups:

* Pairs of mutually exclusive inputs cannot both belong to an all-or-none group, and vice-versa, for example the following is invalid:
```
"groups": [
  {
    "id": "group1",
    "name": "group 1 name",
    "members": ["id2", "id3"],
    "mutually-exclusive": true
  },
  {
    "id": "group2",
    "name": "group 2 name",
    "members": ["id1", "id2", "id3"],
    "all-or-none": true
  }
]
```
* Pairs of inputs in an all-or-none group can't be the only inputs in a one-is-required group, for example the following is invalid:
```
"groups": [
  {
    "id": "group1",
    "name": "group 1 name",
    "members": ["id1", "id2", "id3"],
    "all-or-none": true
  },
  {
    "id": "group2",
    "name": "group 2 name",
    "members": ["id1", "id2"],
    "one-is-required": true
  }
]
```
I can start by doing those rules if they make sense. Are there any more invalid situations we should be aware of?

**Comment by leej3** [comment]
@afni-rickr <https://github.com/orgs/afni/people/afni-rickr> is there any
additional grouping specification that we might need for describing AFNI's
interfaces?
