### ISSUE TITLE
Optionally set environment variables from invocations

### ISSUE THREAD

**Issue by gkiar** [boutiques/boutiques#307]
Can we accept as input environment variables, and set them in the container/environment? Would be potentially useful

**Comment by gkiar** [comment]
This issue came up again recently for me when building a tool that uses environment variables to determine an execution mode. I think it's time this was rolled in, and it'd be nice to be supported before release `v1.0.0`, as it would potentially break the structure of invocations.

My current thought is that we could do one of three things:
1. Accept a list of two elements as an invocation, where the first is the command argument dictionary, and the second is the environment variables list-of-dicts matching to how they're defined in the descriptor. Any value not provided for environment variables would use the default. If we require this structure, it breaks backwards compatibility. If it's optional, then there is internal inconsistency that may be confusing for people including ourselves.
2. Force non-overlapping naming not only within command-line keys and ids but with environment variables as well, and then accept values within the invocation that correspond to the environment variables. This is the simplest solution from a user perspective and preserving backwards compatibility of invocations, but obfuscates what an invocation *means*, as it is no longer just describing the command-line.
3. Support users providing an additional json file that contains environment variables they wish to override or set, following the same structure as within the descriptor. This is perhaps as simple as 2., and preserves invocations in their current state.

I think I went into the above leaning towards 2., and came out thinking 3. is the obvious answer :)

@glatard, thoughts?

**Comment by glatard** [comment]
Following discussion at the meeting today: how about we allow environment variable values to contain command-line keys that would be substituted at runtime using input values? In that way we could still benefit from input validation and use the same invocation format. 
@gkiar @ramou @shots47s what do you think?

**Comment by ramou** [comment]
I've been thinking of this as a replacement for including explicit environment variable setting in the invocation's command-line itself. That's gross, but gives you all the same validation. In that vein, if default environment variables were included in the input, but there was a flag to indicate that it was an environment variable, then it just wouldn't be checked for in the provided command-line, we'd discretely do that behind the scenes to avoid the mess.

I've created a pseudo-fake example where a tool checks for a TRANCEP_DIR environment variable to do something during runtime.

```
{
    "tool-version": "v1.0",
    "name": "TranCEP",
    "author": "Alballa M, Aplop F, Butler G",
    "command-line": "TranCEP.R [INPUT] [OUTPUT_DIR]",
    "container-image": {
        "type": "singularity",
        "image": "bioinformatics-group/TranCPE",
        "index": "shub://",
        "container-opts": [
                "-H $PWD"
        ]
    },
    "description": "Predicts the protein classification for provided sequences.",
    "inputs": [
        {
        	"command-line-flag": "-query",
        	"command-line-flag-separator": "=",
            "description": "A file containing one or more input sequences in fasta format",
            "id": "input",
            "name": "Input Sequences",
            "optional": false,
            "type": "File",
            "value-key": "[INPUT]"
        },
        {
        	"environment-var": "TRANCEP_DIR",
            "description": "The directory where the base TranCEP files are located. Included in the singularity image, so probably avoid changing this unless you know what's up.",
            "id": "trancep_dir",
            "name": "Trancep File Directory",
            "optional": true,
            "type": "File",
            "value-key": "[TRANCEP_DIR]"
        },
        {
        	"command-line-flag": "-out",
        	"command-line-flag-separator": "=",
            "description": "The directory where the results (and intermediate data) are stored. The default location is the same directory as the input sequence.",
            "id": "output_dir",
            "name": "Output Directory",
            "default-value": ".",
            "optional": true,
            "type": "File",
            "value-key": "[OUTPUT_DIR]"
        }
    ],
    "output-files": [
        {
            "id": "outclass",
            "name": "Protein Classification",
            "path-template": "[OUTPUT_DIR]/out.csv",
            "optional": false
        }
    ],
    "schema-version": "0.5",
    "tags": {"domain": ["bioinformatics", "TranCEP"]},
}
```

an invocation of `{"output_dir": ".", "input": "foo.fasta", "trancep_dir": "/usr/bin/TRANCEP"}`

Would create an entry in the script:
```
#!/bin/bash
export TRANCEP_DIR=/usr/bin/TRANCEP
TranCEP.R -query=foo.fasta -out=.
```

The key change is that inputs that include the `environment-var` key (mutually exclusive with `commandline-flag`) would not need confirmation that their value-key existed in the command-line somewhere... if I recall,m other things might still want to know about the value key, so I figured it best to leave. I suspect this is somewhat middle ground between the descriptor and the configuration file approach, though I could be misinterpreting.

**Comment by glatard** [comment]
Hi @ramou, thanks for this! Naive question: why is this better than just supporting command line keys in environment variable values?

**Comment by ramou** [comment]
I think I'd want to see an example of what you mean. It may well be very similar, just a variation on approach.

My understanding was that the main goal was to get the command-line key validation happening with environment variable stuff, so I think there are probably a few equivalent ways to do that sensibly... I want to figure out if what you said was an equivalent way and/or if what I said was sensible :D

**Comment by glatard** [comment]
Hi @ramou, here is an example to what I mean:
```
{
    "tool-version": "v1.0",
    "name": "TranCEP",
    "author": "Alballa M, Aplop F, Butler G",
    "command-line": "TranCEP.R [INPUT] [OUTPUT_DIR]",
    "container-image": {
        "type": "singularity",
        "image": "bioinformatics-group/TranCPE",
        "index": "shub://",
        "container-opts": [
                "-H $PWD"
        ]
    },
    "description": "Predicts the protein classification for provided sequences.",
    "inputs": [
        {
        	"command-line-flag": "-query",
        	"command-line-flag-separator": "=",
            "description": "A file containing one or more input sequences in fasta format",
            "id": "input",
            "name": "Input Sequences",
            "optional": false,
            "type": "File",
            "value-key": "[INPUT]"
        },
        {
            "description": "The directory where the base TranCEP files are located. Included in the singularity image, so probably avoid changing this unless you know what's up.",
            "id": "trancep_dir",
            "name": "Trancep File Directory",
            "optional": true,
            "type": "File",
            "value-key": "[TRANCEP_DIR]"
        },
        {
        	"command-line-flag": "-out",
        	"command-line-flag-separator": "=",
            "description": "The directory where the results (and intermediate data) are stored. The default location is the same directory as the input sequence.",
            "id": "output_dir",
            "name": "Output Directory",
            "default-value": ".",
            "optional": true,
            "type": "File",
            "value-key": "[OUTPUT_DIR]"
        }
    ],
    "environment-variables": [
        {
            "name": "trancep-dir",
            "value": "[TRANCEP_DIR]"
        }
    ],
    "output-files": [
        {
            "id": "outclass",
            "name": "Protein Classification",
            "path-template": "[OUTPUT_DIR]/out.csv",
            "optional": false
        }
    ],
    "schema-version": "0.5",
    "tags": {"domain": ["bioinformatics", "TranCEP"]},
}
```

**Comment by ramou** [comment]
Yep, that's what I'd be looking for, I think.
