### ISSUE TITLE
Make PRs for updated descriptors published to Zenodo

### ISSUE THREAD

**Issue by erinb90** [boutiques/boutiques#320]
The descriptors published as part of #174 were modified to incorporate the changes made in issues #317 and #319. These modifications do not comply with the descriptor schema of the current Boutiques release (0.5.13). Once the schema changes are released, we should make PRs to each hosting repository with the updated descriptors.

**Comment by glatard** [comment]
Release 0.5.14 is now up, issue unlocked!

**Comment by erinb90** [comment]
https://github.com/aces/cbrain-plugins-neuro/pull/133
https://github.com/big-data-lab-team/cbrain-plugins-hcp/pull/29
https://github.com/neurodata/boutiques-tools/pull/9
https://github.com/BIDS-Apps/example/pull/23
https://github.com/big-data-lab-team/cbrain-plugins-eeg/pull/7

**Comment by glatard** [comment]
Closing this, we'll follow up through the other PRs.
