### ISSUE TITLE
Add more keywords to Zenodo metadata

### ISSUE THREAD

**Issue by erinb90** [boutiques/boutiques#328]
The publisher should add more keywords when generating the metadata, such as:
* Tests y/n

@glatard are there any others? Tests is the only one not already there from the list you mentioned in #323

**Comment by glatard** [comment]
Perhaps these ones:
* descriptor-url
* tool-doi

**Comment by erinb90** [comment]
@glatard Do you mean to add a keyword `descriptor-url` if the descriptor specifies one, or add a keyword with the actual URL, e.g. `descriptor-url:http://github.com/...`. Same question for `tool-doi`

**Comment by glatard** [comment]
I think these links should be added to `has-part`.

**Comment by erinb90** [comment]
They are already part of `has-part`. So I guess we just need to add tests:y/n?

**Comment by glatard** [comment]
ok!
