### ISSUE TITLE
bosh exec launch produces a command line where no optionals have their default

### ISSUE THREAD

**Issue by shots47s** [boutiques/boutiques#338]
Using the boutiques descriptor at doi 1484547, if an input element is optional and there is a default-value given, the item does not appear on the command line in the temp work script.

So using this descriptor, and this input json:

{
"bids_dir":"d005",
"analysis_level":"participant",
"participant_label":["02"],
"license_file": "/home/users/sbrown/freesurfer/license.txt",
"output_dir":"b2-out"
}

I get the following command line in temp file:
`mkdir -p b2-out ; /run.py d005 b2-out participant --participant_label 01       --license_file /home/users/sbrown/freesurfer/license.txt`

This would imply that optional variables will never get set to defaults and seems like a weird syntax.

**Comment by glatard** [comment]
Currently the default value is only added to mandatory parameters when they have no value. It's easy to change but I'm not sure of the implications of that yet.

**Comment by shots47s** [comment]
Well, in the case of the bids apps, the run.py has the default values, so it is moot.  But I would think it is a matter of the boutique descriptor being a standalone representation of the full command line.  So technically, I guess the value is not "optional" if it has a default, because by definition you are saying the variable has to have a value, and if you don't specify, then this is the value that it needs to be.  So I think that I am wrong in my question and your current default is correct.  Had to have you ask the question to make me realize the answer.  

Thanks for indulging.

Would suggest no change, clear documentation on this matter (as it is not clear from the schema or current docs that this is the case) and closing this issue.

**Comment by glatard** [comment]
Then to make it clear, shall we prevent optional inputs to have a default value?

**Comment by glatard** [comment]
Add a property `internal-default-value` to specify the value that will be used internally for optional inputs when value isn't specified.

**Comment by erinb90** [comment]
@glatard On this topic, I'm wondering if there is a bug in the normal behavior or if I'm just doing something wrong? If I try removing `str_input` from `invocation.json`, it should use the default value which is "aStringValue". But instead I get the following error on `bosh exec simulate`:

```
u'str_input' is a required property

Failed validating 'required' in schema:
    {'$schema': 'http://json-schema.org/draft-04/schema#',
     'additionalProperties': False,
     'allOf': [{'anyOf': [{'required': [u'num_input']},
                          {'required': [u'enum_input']}]}],
     'dependencies': {u'enum_input': {'properties': {u'num_input': {'not': {}}}},
                      u'flag_input': {'anyOf': [{'properties': {u'num_input': {'not': {}}},
                                                 'required': [u'file_input']},
                                                {'properties': {u'flag_input': {'enum': [False]}}}]},
                      u'num_input': {'properties': {u'enum_input': {'not': {}}}}},
     'description': 'Invocation schema for example boutiques tool.',
     'properties': {u'config_num': {'enum': [4]},
                    u'enum_input': {'enum': [u'val1', u'val2', u'val3']},
                    u'file_input': {'type': 'string'},
                    u'flag_input': {'type': 'boolean'},
                    u'list_int_input': {'items': {'type': 'integer'},
                                        'minItems': 1,
                                        'type': 'array'},
                    u'num_input': {'exclusiveMinimum': True,
                                   'maximum': 1,
                                   'minimum': 0,
                                   'type': u'number'},
                    u'str_input': {'type': u'string'},
                    u'str_input_list': {'items': {'type': u'string'},
                                        'maxItems': 3,
                                        'minItems': 1,
                                        'type': 'array'}},
     'required': [u'str_input_list',
                  u'str_input',
                  u'list_int_input',
                  u'config_num'],
     'title': 'Example Boutiques Tool.invocationSchema',
     'type': 'object'}

On instance:
    {u'config_num': 4,
     u'enum_input': u'val1',
     u'file_input': u'./setup.py',
     u'list_int_input': [1, 2, 3],
     u'str_input_list': [u"fo '; echo FAIL", u'bar']}
```

**Comment by glatard** [comment]
Yeah I think it's a bug: the invocation validator should replace the default values before it checks if the invocation is valid. It's not so straightforward to fix as it requires the logic handling default values to be moved out of `localExec.py`. Do you see what I mean? And great catch!
