### ISSUE TITLE
BGraph, a graph of Boutiques descriptors, invocations, and result objects

### ISSUE THREAD

**Issue by glatard** [boutiques/boutiques#344]
As discussed with @ValHayot, we could leverage Zenodo to create BGraph, a graph of Boutiques invocations, results and descriptors. Among other applications, this graph could be used to measure tool usage, to identify related users, platforms and tools (communities), to find important tools and files, and to measure redundancy of computations between platforms or users. Platforms such as CBRAIN and VIP could publish all their invocations and results periodically. `bosh` could also encourage users to publish their objects.

The following features would have to be developed.

1. Publish invocations

Invocations could be published in a way similar to descriptors. Before publishing an invocation, file names should be replaced by checksums, or rather, a new object should be added that contains the checksums. In the future, checksums could be replaced by a LSH that would allow to estimate the distance between images from their hashes.

2. Publish result objects

Result objects produced by `bosh exec` should be serialized to JSON. It should be possible to publish result objects just like invocations.

3. Caching

Publishing invocations or result objects after every run might not be convenient. For instance, when a run is done on a cluster, it is common that worker nodes don't have remote connectivity. Invocations and result objects should remain cached under `.cache/boutiques` so that they can be published all at once, for instance from the cluster head node. Perhaps tool descriptors that don't have a DOI could also be cached there, for later publication.

4. Automated publication

A flag should be available to automatically publish any new invocation, result object, or descriptor. Perhaps a flag should be available to *disable* publication but that might be a bit aggressive. In addition, commands launched in a tty should periodically walk through the cache and offer the option to publish all invocations, result objects and descriptors. Finally, `bosh publish` should do that if called without option (and ask confirmation before publishing unless called with `--noint`).

@jbpoline @shawntbrown @erinb90 @gkiar @ValHayot @camarasu, what do you think?

**Comment by glatard** [comment]
This graph would also be a way to identify candidate tools to be used for a particular dataset, as discussed with @jbpoline and @shots47s yesterday.

**Comment by ValHayot** [comment]
Resource consumption(e.g. walltime, memory, IO) should be added to the BGraph output to enable potential optimizations based on resource usage statistics.

**Comment by gkiar** [comment]
@ValHayot these values aren't currently collected by Boutiques, but are by Clowdr (and presumably all the tools you've made using Boutiques). @glatard and I are planning to strengthen the relationship between Clowdr and Boutiques, so eventually this can be part of a command something like `bosh exec launch --cluster`.

**Comment by shots47s** [comment]
@glatard, @ValHayot, at @gkiar, would this be a place that any tool could send these results.  This could be extremely helpful for orchestration tools like CBRAIN to be able to predict length of runs and what machines to place pipelines on. Since we will be shortly using bosh to launch pipelines, we should be able to contribute, but as @gkiar said, Singularity doesn't collect this info, so something would need to be done to do that.

**Comment by glatard** [comment]
yes, invocations and outputs would be published to Zenodo. @gkiar, is clowdr's performance monitoring something that we could easily add to bosh? I feel like it would be the right place, since monitoring isn't really bound to cluster/cloud execution.

**Comment by gkiar** [comment]
@glatard yeah - it was a bit tricky to get right initially, but I could add 1 file to the package that is something like `monitor.py` which is actually called by `bosh` with the intended arguments, and in turn calls `localExec.py`. I expect this would take me 1-2 days of work and debugging inevitable copy-paste errors before having a functioning PR.

**Comment by glatard** [comment]
Amanda could work on that in her course project on BGraph. We will summarize the plan here when it's more settled.

**Comment by jbpoline** [comment]
@glatard  @gkiar : making sure I got that right:  the nodes of the graph are made with the datalad unique ids (in the .datalad/...json) ?

**Comment by gkiar** [comment]
No, @jbpoline, they are published on Zenodo using `bosh publish`.

**Comment by jbpoline** [comment]
Ha, yes of course. May be worth to think about that in the future: I have a datalad dataset, can I search for the tools that have processed it ...

**Comment by glatard** [comment]
execution output objects should also include a status code (success or failure).

**Comment by gkiar** [comment]
Yep - I would also suggest keeping everything we dump to the screen after verbose execution now, such as the command-line as it was substituted, the std-out, the std-error, and any custom error message provided by the descriptor

**Comment by friesenA** [comment]
So here is the current plan for my project, critique welcome.

1. Define basic data capture json object (invocation and outputs)
2. Collect and save data capture obj in a cache upon execution
3. Hashing of input and output files for data capture obj
4. Add to output log a message to suggest publication of cache, listing # of entries
5. Add command to review cache and subcommands:
    inspect: view files in cache
    publish: publish cache as one data-set or individual data-sets
6. Add subcommands:
    configure: set author
    remove: one file or all files
7. On publishing data-set, Descriptors without DOI's are held and published before data-set to update data capture obj with correct DOI value then the data-set is published
8. Add weekly prompt to publish
9. Add automatic publishing as a configure option, publishes once a week, disables prompts

**Comment by friesenA** [comment]
5 and 7 are separate for sake of modularity of development, since 7 is fairly complex in itself. But it is correct that the feature is not releasable until after step 7 because that case needs to be handled.

9 could offer both single and bulk publishing as a config option without adding much work, I was not thinking of a daemon but of the same check system that would be used for the weekly prompt.

the suggestion of a flag in bosh.exec is intended to publish that invocation immediately after execution? I will add that as a separate step.

**Comment by glatard** [comment]
OK, sounds good! We can talk again about the flag when you're there, there might be a few details to pay attention to.
