### ISSUE TITLE
Add a property for online platform(s) having the tool installed

### ISSUE THREAD

**Issue by glatard** [boutiques/boutiques#359]
Add a property `online-platforms` containing a list of URLs where the descriptor is installed and available. Upon publication, the elements in this list should be added to the 'hasPart' list in Zenodo. That would allow users to be pointed to CBRAIN, VIP and other platforms where the descriptor can be found. As discussed with @shots47s during the CONP meeting today.

**Comment by glatard** [comment]
This is now critical to the integration of Boutiques tools in CONP. We'd like to be able to leverage that for the April 15th CONP prototype.

**Comment by paiva** [comment]
@glatard why is this issue now closed?
