### ISSUE TITLE
search doesn't search on tool names

### ISSUE THREAD

**Issue by glatard** [boutiques/boutiques#363]
For instance, `bosh search fsl` doesn't return tools named `fsl_fast`, `fsl_first`, etc

```
$ bosh search fsl
Showing 1 of 1 results.
ID              TITLE    DESCRIPTION
zenodo.1482743  fsl_bet  Automated brain extraction tool for FSL
```

I'm not sure if this is an issue with Zenodo's search or with the query in `bosh search`.

**Comment by erinb90** [comment]
Seems to be an issue with Zenodo's search, cause the same thing happens if you search for "fsl" normally without the API: https://zenodo.org/search?page=1&size=20&q=fsl&keywords=boutiques&keywords=schema&keywords=version&file_type=json&type=software

**Comment by glatard** [comment]
So perhaps that's something that could be investigated with the Zenodo support? Worst case, we could add the tool name to the description, for instance: "Boutiques descriptor for <tool_name>. <description>.", before publishing it.

**Comment by erinb90** [comment]
Ok, I sent a message to Zenodo support asking about it.

**Comment by erinb90** [comment]
Reply from Zenodo support:

"Dear Erin,

First of all thanks for your feedback.
This is actually the intended behavior, as part of your elasticsearch analyzer configuration. This results in a tradeoff between performance and flexibility for the user.

Best regards,
Francois"

**Comment by gkiar** [comment]
So, should we just add the tool name as a tag when pushing to Zenodo, getting a free search on it there?

**Comment by glatard** [comment]
Adding stuff to the description, as mentioned above, sounds right indeed. But before that, @erinb90 do you know if the description is the *only* field on which search occurs? It seems that we can't search on tags either:
```
$ bosh search neuroinformatics
[ INFO ] Showing 1 of 1 results.
ID              TITLE    DESCRIPTION
zenodo.1451003  qeeg     qeeg application
```
But that we can search on container images, presumably through tags: `bosh search docker` and `bosh search singularity` return what we expect. Not sure what is going on here...

Overall, we need to be able to search on name, description, and tags (including the boutiques tags and the ones we add to Zenodo). And we don't want to have to distinguish between these fields when searching (e.g., no `bosh search --name fsl`). If adding to the description is the only solution, then so be it. If you find a better way, even better!

**Comment by gkiar** [comment]
While I agree another way would be even better, if this ends up being the case we could just run a quick `pprint` on it and extract everything between the first and second `====` separators, which covers our bases? ([the contents of that range is here](https://github.com/boutiques/boutiques/blob/master/tools/python/boutiques/prettyprint.py#L82-L83))

**Comment by erinb90** [comment]
`bosh search docker` and `bosh search singularity` return what we expect because the exact tags are `docker` and `singularity`. Searching for `neuroinformatics` doesn't work because the tag is `domain:neuroinformatics`. So we can only find tags by exact match.

I guess we can only search on the description, then. I'm not too big on the idea of adding the tool name to the description, but I can't think of a better way.

**Comment by glatard** [comment]
`bosh search "domain:neuroinformatics"` doesn't match either, perhaps due to the colon?

**Comment by erinb90** [comment]
According to [this](https://stackoverflow.com/questions/13168666/python-argparse-argument-with-quotes), using backslashes is the best way to preserve quotes around an argument. I tried `bosh search \"domain:neuroinformatics\"` and it indeed returned the desired results. I can mention this in the help text so it's clear. 

Anyways, I still don't know a good way to get around the fact that we can't search on titles and tags. I think the only way is to add the title and tags to the description when publishing, but this will look redundant and ugly. Zenodo just has a bad search API and there's not much we can do :(

**Comment by glatard** [comment]
Thanks for looking into this. I think we want to add the name and tags to the description indeed, nevermind the bad-looking interface in Zenodo. I find it more important to be able to retrieve tools. What do you think @gkiar?

**Comment by glatard** [comment]
Since we're at it, I think we might want to add "Boutiques" to the title of the published applications. For instance, looking for "fmriprep", for now the Boutiques descriptor can't be easily distinguished from the actual fmriprep code in the Zenodo interface. How about appending (Boutiques descriptor) to the tool name upon upload, and removing this string in search?

**Comment by gkiar** [comment]
I'm with @glatard in that I'd rather have it clunky in the web but functional on the CLI. Also agree about adding a `(Boutiques descriptor)` at the end of even title when publishing, and stripping them out in `bosh search` display so we don't waste characters all the time

**Comment by glatard** [comment]
and searching on for "*neuroinformatics" also returns the tools with tags "domain:neuroinformatics". So the API does search on name and tags, it's just that it's looking for exact matches... @erinb90, what do you think of just prepending and appending stars to the query by default, and adding an option for exact match?

Great catch @ramou, thanks!

**Comment by erinb90** [comment]
I like that idea! Thanks @ramou, that is very useful info!
