### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by erinb90** [boutiques/boutiques#370]
Update the Boutiques README with new functions like `bosh search`, `bosh pull`, etc.

**Comment by erinb90** [comment]
I see that `bosh search` is already described. Do we need to talk about `bosh pull`? I feel like there aren't many use cases where someone would want to use `bosh pull` on its own. It will typically be done in the background when passing Zenodo IDs to the various bosh commands.

**Comment by glatard** [comment]
agreed.

**Comment by erinb90** [comment]
Ok, I still see two very very minor fixes (`$ bosh search fsl` needs an indent, list of dependencies should be updated). I can just include those in my next PR.
