### ISSUE TITLE
`bosh example` should produce invocations with no optional parameter

### ISSUE THREAD

**Issue by glatard** [boutiques/boutiques#373]
This would make it easier for users to start from a minimal invocation when tool has a lot of optional parameters. A flag, for instance `-c` or `--complete` would trigger complete invocations, including optional parameters.

**Comment by DarrinFong** [comment]
I don't quite understand the term invocation in this issue (or inside of boutiques)

After this issue is implemented, does it mean the JSON output of __this__ command will contain the most basic parameters?

```
bosh example good.json
{
    "non_optional1": "foo",
    "non_optional2: "bar"
}
```
and with the ```--complete``` flag, the result would be
```
bosh example -c good.json
{
    "non_optional1": "foo",
    "non_optional2: "bar",
    "optional1: "foo",
    "optional2: "bar"
}
```

**Comment by glatard** [comment]
yes exactly! Assuming that "most basic parameters" means "non-optional parameters".

**Comment by DarrinFong** [comment]
How do I determine which param in the mutex group to take? 
For example which one between these two in good.json
```
{
    "dti_file": "f_dti_file_65.nii.gz",
    "dti_file_minc": "f_dti_file_minc_85.j"
}
```

**Comment by glatard** [comment]
I would just pick one randomly.
