### ISSUE TITLE
bosh is incapable of providing its own version

### ISSUE THREAD

**Issue by prioux** [boutiques/boutiques#377]
I tried:

```shell
bosh -v
bosh -V
bosh --version
bosh --v
bosh version
```

and all of them just provided the same usage statement. For provenance recording and automatic pipelines, it would be good if at least one of them would print out, on a single line, something like

```
0.5.18
```

so that the invoking context could capture and record that.

**Comment by glatard** [comment]
Thanks for mentioning this @prioux 

Note to whoever will do this: 
* The flag should be `--version` as `-v` is already used for verbose mode.
* The version string should be consistent with the one in `setup.py`, i.e., it should be written only once.
