### ISSUE TITLE
pprint crashes on zenodo.2541125

### ISSUE THREAD

**Issue by glatard** [boutiques/boutiques#388]
Perhaps related to #386 but unlikely.
How to reproduce:
![screenshot from 2019-01-18 22-18-40](https://user-images.githubusercontent.com/5174953/51421646-235b0c00-1b6f-11e9-8ac9-42ca9d7aca80.png)

**Comment by erinb90** [comment]
I just tried this and it didn't crash. Can this issue be closed?
