### ISSUE TITLE
Export descriptor from docopt

### ISSUE THREAD

**Issue by glatard** [boutiques/boutiques#392]
http://docopt.org

**Comment by gkiar** [comment]
Yeah - pretty print is using the standard argparse formatting for parameters, so when we support one of creating descriptors from docopt or pretty print, we get the other essentially free

**Comment by edickie** [comment]
ps we found out this is a little harder than we thought. Would be great though! pretty please!

**Comment by glatard** [comment]
Hi @edickie could you post a summary of what you tried and why it turned out to be harder than expected?

**Comment by edickie** [comment]
We thought we could convert from docopt to an argparse object but it turns out no..so now I'm back to writing the .json from scratch

**Comment by glatard** [comment]
Hi @edickie, could you provide an example of a docopt script to be converted?

**Comment by edickie** [comment]
Thanks. I have the draft boutiques bosh for the bidsapp and the script in
this branch

https://github.com/edickie/ciftify/tree/enc_addboutique_spec/ciftify/bidsapp


I would love to draft more boutiques spec around most of the stuff in the
bin/ for this project. (it's all docopt).
https://github.com/edickie/ciftify/tree/enc_addboutique_spec/ciftify/bin

**Comment by DarrinFong** [comment]
Hi, I don't quite understand this issue after having read about docopt. My interpretation is that we want to use docopt's parser instead of argparse's to generate a descriptor json file. 

May I get an example of the command to run which requires some parsing by argparse? It seems like just running ```bosh create x.json``` generates a default sample descriptor.

**Comment by glatard** [comment]
Your interpretation is correct: we want to be able to export a descriptor from a Python script that has its input/output parameters described with docopt. 

Similarly to argparse, export from docopt should work from a Python code, not from the command line. The example usage from README.md is:
```
import boutiques.creator as bc
newDescriptor = bc.CreateDescriptor(myparser, execname="/command/to/run/exec")
newDescriptor.save("my-new-descriptor.json")
```
Currently `myparser` has to be an `argparse` parser. `bc.CreateDescriptor` should work similarly with some docopt object.

**Comment by glatard** [comment]
Just chatted with @gkiar about this issue. It would be nice to convert the docopt object to an argparse parser, so that `CreateDescriptor` could work consistently for both formats. There might be existing code to convert from docopt to argparse, btw.

**Comment by edickie** [comment]
That would be great! My reading of the docopt code made me think it might
be harder to do. But I'm excited with there is already a docopt-to-argparse
that might work.
