### ISSUE TITLE
passing the zenodo ID for bosh publish

### ISSUE THREAD

**Issue by shots47s** [boutiques/boutiques#396]
When trying to update an existing descriptor in Zenodo, I am having trouble with it not finding the previous descriptor, and therefore created a new one.  I think it would be great if we could add a command line argument to bosh publish that specifies the Zenodo ID that we want to publish. There are drawbacks, as it could potentially squash another descriptor that is already there, but it would be a more exact way to ensure we are not creating duplicates in Zenodo.

**Comment by glatard** [comment]
Hey @shots47s, thanks for reporting this, we already have an issue on that in #393, I faced the exact same problem while working with a friend yesterday :)
