### ISSUE TITLE
Support basenames and wildcards in output files

### ISSUE THREAD

**Issue by gkiar** [boutiques/boutiques#397]
Currently, in `output-files` we cannot use the `basename` of a parameter in substitution, or a `*` (wildcard).

Supporting wildcard seems easy - we just need to `glob` for the files after the templates are created.

For supporting `basename`s, we could add the following logic:
1. the `uses-basename` parameter added to `output-files`
2. when doing substitution, if this flag is set, all inputs of type `File` used in the `path-template` will be stripped to their basename before substitution (`path-template-stripped-extensions` will still be applied after this is done).
3. If you really want to half-use this feature, and only use the basename for one file and full path for another in the same output file name, you can make the input type of the file you'd like not to be reduced a `String` instead. This of course looses 1 step of input validation in that case at the cost of output validation, but is also a somewhat ridiculous use case that shouldn't come up often.

**Comment by ramou** [comment]
For reference, this is the example I found for concisely applying wildcard searches that I think would be consistent with the above:
https://stackoverflow.com/questions/4296138/use-wildcard-with-os-path-isfile#4297946

**Comment by glatard** [comment]
isn't it reasonable to assume that basenames will always be used when the value-key isn't a prefix of the template? And that when the value-key is a prefix, we use the value as is?

**Comment by gkiar** [comment]
To be clear @glatard - you're saying if the `path-template` starts with some command-line key for a file, don't strip down to the basename, otherwise, always do? I support that.

**Comment by glatard** [comment]
yes, that's what I mean. The rationale is that not stripping the basename should never hurt when the path is at the beginning of the template. And not stripping will always hurt when the path is in the middle of the template.

**Comment by ramou** [comment]
Would it be weird to ask for examples of the different ways it could go and how it is expected that boutiques should interpret it?

**Comment by glatard** [comment]
Sure, say that we have a value-key [FILE] mapped to value "/home/foo/file.txt", with stripped extensions containing "txt", then:
- `[FILE]_result.gz` would resolve to `/home/foo/file_result.gz`
- `result-[FILE].gz` would resolve to `result-file.gz`

**Comment by gkiar** [comment]
Agreed. So this issue is just to implement that behaviour and fix wildcarding.

**Comment by erinb90** [comment]
We might also want to exclude paths containing wildcards when validating that all output path templates are unique. For example, one of my descriptors produced from a Nipype interface had several output lists whose files all had extension `.nii`. So I put `*.nii` as the path template for all of them, but this doesn't validate for path template uniqueness.

**Comment by ramou** [comment]
Is it too much to wish for a notation that we could apply to any/all value keys that would apply regular expression search/replace with fancy capture groups, or would that entirely upend making things clear and explicit? I'm not entirely joking as I like having that kind of power available, so long as I also have a convenient default that covers most regular usage.

**Comment by ramou** [comment]
I can't wait for this, because I think technically [AQUA.tcl](https://github.com/bioinformatics-group/BoutiquesDescriptors/blob/master/AQUA/1.1/AQUA.tcl.json) will be broken for some inputs if this isn't done :\ Poking at this has just become more appealing as a suitable not-writing procrastination.

**Comment by gkiar** [comment]
Going to implement this now because I need it for a couple of descriptors I'm working on 😸

**Comment by gkiar** [comment]
> We might also want to exclude paths containing wildcards when validating that all output path templates are unique. For example, one of my descriptors produced from a Nipype interface had several output lists whose files all had extension `.nii`. So I put `*.nii` as the path template for all of them, but this doesn't validate for path template uniqueness.

@glatard @erinb90 I don't think we can/want to support these being identified as unique files if they truly do match in their entirety - because then we can't validate that which of the output files exists, and therefore that validation after run-time is almost more harmful than no output files being specified at all. Currently, wildcards *within* path templates are searched/found on validation (I verified this when workign on #527), so even doing something like `"path-template": "*mask*.nii*"` would be possible, if that's all the info we can get from the interface. But if my tool creates 1 nifti file, I don't want to be told that all my outputs specified only as `*.nii` are there and not having an idea which it is.

Am I misunderstanding something/does that make sense?

**Comment by glatard** [comment]
Decision from the meeting: all path templates have to be different, even if using wildcards.
