### ISSUE TITLE
The URLs in the schema are all wrong.

### ISSUE THREAD

**Issue by prioux** [boutiques/boutiques#400]
I'm looking at the schema, and it contains a bunch of GitHub URLs for the IDs of the entries, and none of them map to anything actually on GitHub.

**Comment by prioux** [comment]
Schema here:

https://github.com/boutiques/boutiques/blob/master/tools/python/boutiques/schema/descriptor.schema.json

**Comment by glatard** [comment]
These are supposed to be identifiers (URIs), not necessarily URLs.

**Comment by prioux** [comment]
Okay.... :-(
