### ISSUE TITLE
Is output-files optional or not?

### ISSUE THREAD

**Issue by prioux** [boutiques/boutiques#401]
The text description of the schema says that output-files is optional, yet the schema makes it mandatory with at least one entry in it:

https://github.com/boutiques/boutiques/tree/master/schema#output-files

vs

https://github.com/boutiques/boutiques/blob/master/tools/python/boutiques/schema/descriptor.schema.json#L621

**Comment by glatard** [comment]
I think it's consistent: it means that the array may or may not be present, but when it is present it cannot be empty.

**Comment by prioux** [comment]
Hum, OK, I asked because I got validation errors on a modified descriptor where I removed the entry and left an empty array. I'll try to remove the array when nothing's left. If that works, I'll close this issue.

**Comment by prioux** [comment]
OK, handled.
