### ISSUE TITLE
The semantics of bosh --imagepath is wrong

### ISSUE THREAD

**Issue by prioux** [boutiques/boutiques#405]
The bosh subcommands `prepare` and `launch` both support the option `--imagepath`.

It is terrible to use.

First, counter intuitively, the option is not the path to an image file, it is that path to the directory where that image is stored. It should be called 'imagedir'!

Second, when an external system wants to prepare an execution, it makes it impossible to find the name of the image file without guessing. One has to first, make up a list of the files in the target directory, then invoke the prepare command, then read again the target directory to find out the name of the image file. And that is, assuming that in the meantime only one new file will have been created and it happens to be the image. Of course the invoker could parse the message that bosh prints out when it's done, but that message is a) for humans, and likely to change 2) is not the same with the prepare command has pulled the image vs when the image was already found in the directory.

The proper behavior would have been for the `--imagepath` option to specify the path to the image file itself, chosen by the invoker. That allows the invoker to give it a name of its own choosing, to verify that the image was pulled properly, and even to override the image specified in the descriptor with another image if necessary.

**Comment by prioux** [comment]
Greg tells me that for ‘launch’ it is the path to the image, that’s good. Only  ‘prepare’ needs to be fixed.

**Comment by erinb90** [comment]
I made the option be the directory name because I didn't realize you could specify a different image name when pulling an image, but now I see there is a `--name` option for `singularity pull` that lets you specify the image name. So I think we can use that to pull the image with any name we want.

**Comment by erinb90** [comment]
Also, to set the singularity pull folder you need to supply the directory name, so the simplest thing was just to have the user supply that. But it should be easy enough to have the user supply the full path and get the directory name from there.

**Comment by shots47s** [comment]
So.. is the solution to make --imagepath specify a specific image or to make --imagedir and a separate flag that will provide the name of the singularity image? It is advantageous for us to have the prior as we would like to pull and cache the singularity image so that we do not need to pull it every time we run something and do not need to do extra parsing to find the name of the image.

**Comment by glatard** [comment]
So let's fix prepare so that `--imagepath` takes the path of the image instead of the directory.

**Comment by prioux** [comment]
There is still abug when the path is a plain basename (discussed in https://github.com/boutiques/boutiques/issues/404#issuecomment-464502819 ).Maybe the comments I made over there should have been here.

**Comment by glatard** [comment]
Closing this, leaving #404 open to track the path issues for lockdir creation.
