### ISSUE TITLE
"bosh exec launch" doesn't work at all as soon as one specifies "-v"

### ISSUE THREAD

**Issue by prioux** [boutiques/boutiques#408]
Bug report on version 0.5.18 in branch 'develop'.

The "-v" option of `bosh exec launch` is supposed to provide the user with a way to specify mount points when launching the tool within a container. The help description says:

```
unix> bosh exec launch -h
usage: Launches an invocation. [-h] [-v [VOLUMES [VOLUMES ...]]] [-x] [-u]
                               [-s] [--imagepath IMAGEPATH]
                               descriptor invocation

positional arguments:
  descriptor            The Boutiques descriptor as a JSON file, JSON string
                        or Zenodo ID (prefixed by 'zenodo.').
  invocation            Input JSON complying to invocation.

optional arguments:
  -h, --help            show this help message and exit
  -v [VOLUMES [VOLUMES ...]], --volumes [VOLUMES [VOLUMES ...]]
                        Volumes to mount when launching the container. Format
                        consistently the following: /a:/b will mount local
                        directory /a to container directory /b.
  -x, --debug           Keeps temporary scripts used during execution, and
                        prints additional debug messages.
  -u, --user            Runs the container as local user (prioux) instead of
                        root.
  -s, --stream          Streams stdout and stderr in real time during
                        execution.
  --imagepath IMAGEPATH
                        Location of Singularity image (default is current
                        directory).
```

Instead, as soon as the first option "-v" is found, it swallows all other arguments on the command-line, making the program complain of not having enough arguments:

```
unix> bosh exec launch -v /a:/b boutiques.json invoke.json
usage: Launches an invocation. [-h] [-v [VOLUMES [VOLUMES ...]]] [-x] [-u]
                               [-s] [--imagepath IMAGEPATH]
                               descriptor invocation
Launches an invocation.: error: too few arguments
```

It doesn't matter how many arguments are added after -v, or how often -v is used, as soon as "-v" is parsed, the error occurs. I'm highlighting the slurped arguments below in many artificial examples, just to highlight how greedy it is.

* bosh exec launch -v `boutiques.json invoke.json`
* bosh exec launch -v `abc boutiques.json invoke.json`
* bosh exec launch -v `abc def boutiques.json invoke.json`
* bosh exec launch -v `abc -v def boutiques.json invoke.json`
* bosh exec launch -v `abc def xyz hello how are you boutiques.json invoke.json`
* bosh exec launch -v `abc:def -v xyz:hello -v how are you boutiques.json invoke.json`

The problem occurs in the argument parsing, of course. I'm not a python programmer but I suspect it's caused by the `nargs="*"` at line 110 of bosh.py :

https://github.com/boutiques/boutiques/blob/master/tools/python/boutiques/bosh.py#L110

My suggestion is to make "-v" a repeatable option that takes a single value, like it is for singularity (multiple -B) and docker (multiple -v), or tar and rsync (multiple --exclude and --include):

```
bosh exec launch -v mountspec1 -v mountspec2 -v mountspec3 boutiques.json invoke.json
```

**Comment by prioux** [comment]
Well, I'm learning python.

The solution is to remove `nargs="*"` completely and change `action="append"` (instead of store).

Then results.volumes will be an array of each of the values for the  each "-v".

**Comment by prioux** [comment]
```diff
diff --git a/tools/python/boutiques/bosh.py b/tools/python/boutiques/bosh.py
index 0ca9906..988e770 100755
--- a/tools/python/boutiques/bosh.py
+++ b/tools/python/boutiques/bosh.py
@@ -103,11 +103,11 @@ def execute(*params):
                             "JSON string or Zenodo ID (prefixed by 'zenodo.').")
         parser.add_argument("invocation", action="store",
                             help="Input JSON complying to invocation.")
-        parser.add_argument("-v", "--volumes", action="store", type=str,
+        parser.add_argument("-v", "--volumes", action="append", type=str,
                             help="Volumes to mount when launching the "
                             "container. Format consistently the following:"
                             " /a:/b will mount local directory /a to "
-                            "container directory /b.", nargs="*")
+                            "container directory /b.")
         parser.add_argument("-x", "--debug", action="store_true",
                             help="Keeps temporary scripts used during "
                             "execution, and prints additional debug "
```

**Comment by glatard** [comment]
Thanks for reporting this @prioux. Before it's fixed, one can work around it by using another option after `-v`, for instance `-x` or `-s`.

**Comment by gkiar** [comment]
This can also be addressed by putting the `-v` after all the positional arguments, which is the common mode of operation for Python scripts (while I recognize, @prioux , this is counter to the standard for unix commands).

**Comment by prioux** [comment]
@glatard and @gkiar : Thanks both.

**Comment by prioux** [comment]
In CBRAIN right now I've added `-u -s` just before the boutiques descriptor so that `-v` stops globbing everything, but that being said I think this bug should be addressed because for many users who are providing `-v` last, it is mysterious why the program fails. A proper separator for ending option parsing is the bare `--`, which ArgsParse support and it works in bosh, but asking users to provide it just in that specific use case is ugly. Like I said my recommendation is separate `-v`, because there is no ambiguity then.

**Comment by prioux** [comment]
I can also imagine something that maybe you guys have not: the case where bosh is invoked to launch several executions:

```bash
bosh boutiques.json invoke1.json invoke2.json invoke3.json
```

This is why options should be before the variable length arguments. I may want one on the invoke JSON files to be called '-v', after all. (It is a legal filename).

**Comment by prioux** [comment]
So what are your thoughts? Should bosh be fixed so that individual -v options are required before each mount point, like it is for singularity (multiple -B) and docker (multiple -v) ?

It is the proper command line API. It also means that if a program already wraps "bosh" but allow adding other command-line options, it will work. E.g. if a program `wrapper.sh` has in it:

```bash
# Launch with one hard coded mount point
bosh exec launch -v /abc:/abc $OTHER_OPTIONS desc.json invoke.json
```

where OTHER_OPTIONS is a variable that a higher context can provide, then that OTHER_OPTIONS can contain additional `-v` and everything will be fine:

```
OTHER_OPTIONS="-s" wrapper.sh   # works fine
OTHER_OPTIONS="-v /def:/def -u -s" wrapper.sh   # works fine too
```

I can make a PR in 3 minutes flat!

**Comment by prioux** [comment]
Oh, I'll just make the PR anyway.

**Comment by glatard** [comment]
Thanks for fixing @prioux.
