### ISSUE TITLE
Fix website to remove any mentioning of Neurolinks

### ISSUE THREAD

**Issue by glatard** [boutiques/boutiques#426]
Refer to Zenodo instead.

**Comment by mathdugre** [comment]
I can take care of it.
If I understand correctly, it would require to modify the boutiques/boutiques.github.io repository?

**Comment by glatard** [comment]
yes!

**Comment by mathdugre** [comment]
Hello Tristan, should we tag this issue as fixed? as well as [issue #6](https://github.com/boutiques/boutiques.github.io/issues/6) on the boutiques.github.io repository.
I'm not sure how to do it
