### ISSUE TITLE
Add a "deprecated" tag to remove tools from search results

### ISSUE THREAD

**Issue by glatard** [boutiques/boutiques#428]
This is coming from the discussion in #402.

That would allow tools to remain accessible on Zenodo for those who know their DOIs. Applications relying on unpublished descriptors would still run, but new ones would be encouraged to use the latest version.

**Comment by glatard** [comment]
Also add a `bosh deprecate` command.

**Comment by mathdugre** [comment]
Could more explanation be provided on the use of `bosh deprecate`; I am not quite sure to understand how a user would use it.

**Comment by glatard** [comment]
I have been working on this issue and will PR soon. The pycon tag should be removed.

**Comment by glatard** [comment]
Link to WIP regarding this issue: https://github.com/boutiques/boutiques/compare/develop...glatard:deprecate?expand=1
