### ISSUE TITLE
Inconsistency in application of invocation quotes causes unexpected behaviour

### ISSUE THREAD

**Issue by ramou** [boutiques/boutiques#432]
When passing a single-quote-encapsulated string in my invocation I had some grief. The shell command told me it was:
```
blast_formatter  -archive out.asn -outfmt '7 qacc sacc evalue qstart qend sstart send'
```
which runs fine live, but gave an error message about formatted arguments from bosh (invoked programatically, though I think that's not an issue). The input of interest is `outfmt`

The invocation was:
```
		"invocation": {
			"archive": "out.asn",
			"outfmt": "'7 qacc sacc evalue qstart qend sstart send'",
			"out": "blast_formatter.out"
		},
```
You can invoke this through the tests (which fail due to the misinterpretation of the quotes), but I had trouble invoking through the command-line as I had to escape the single quotes and that messed stuff up. You can invoke the other variants through the command-line:

```
bosh exec launch ../blast_formatter.json '{"archive": "out.asn", "outfmt": "7 qacc sacc evalue qstart qend sstart send", "out": "blast_formatter.out"}'
```
does not work and yields the same _shell command_ as the broken test invocation above:
```
bin/blast_formatter  -archive out.asn -outfmt '7 qacc sacc evalue qstart qend sstart send'       -out blast_formatter.out
```

On the other hand, the following (which is what I changed the test invocation to in order to make it work) gives the desired result:

```
bosh exec launch ../blast_formatter.json '{"archive": "out.asn", "outfmt": "\"7 qacc sacc evalue qstart qend sstart send\"", "out": "blast_formatter.out"}'
```
works and yields the _shell command_:
```
bin/blast_formatter  -archive out.asn -outfmt '"7 qacc sacc evalue qstart qend sstart send"'       -out blast_formatter.out
```
I think the method by which strings passed as inputs should be quoted could be made explicit to perhaps resolve this interpretation, perhaps with the current default (single-quoting?). However, given that the single-qouted shell-command is actually a lie (not what actually gets run according to my tests), I think there is a problem in how things are being escaped... a quick look at the code makes me think it could be done in a clearer way that shows intent better.

All my tests were in Pthon 2.7. The test invocation and test files can be found [here](https://github.com/ramou/BoutiquesDescriptors/tree/master/ncbi-blast/2.7.1/blast_formatter)
with the desciptor [here](https://github.com/ramou/BoutiquesDescriptors/blob/master/ncbi-blast/2.7.1/blast_formatter.json) or on Zenodo. Related closed issues are #175 and #89.

**Comment by glatard** [comment]
Hi @ramou, I am a bit confused about what is the issue here.

Using your current invocation:
```
{
			"archive": "out.asn",
			"outfmt": "\"7 qacc sacc evalue qstart qend sstart send\"",
			"out": "blast_formatter.out"
		}
```
The command line produced by `bosh` is:
```
init_genpipes -a /tmp/$USER/cvmfs-cache -c /etc/parrot/ /cvmfs/soft.mugqic/CentOS6/software/blast/ncbi-blast-2.7.1+/bin/blast_formatter  -archive out.asn -outfmt '"7 qacc sacc evalue qstart qend sstart send"'  -num_descriptions 500 -num_alignments 250 -line_length 60   -out blast_formatter.out
```
I put single quotes around your double quotst, which I think is correct.

And when the invocation is changed to the following:
```
{
			"archive": "out.asn",
			"outfmt": "7 qacc sacc evalue qstart qend sstart send",
			"out": "blast_formatter.out"
}
```

Then the command line becomes:
```
init_genpipes -a /tmp/$USER/cvmfs-cache -c /etc/parrot/ /cvmfs/soft.mugqic/CentOS6/software/blast/ncbi-blast-2.7.1+/bin/blast_formatter  -archive out.asn -outfmt '7 qacc sacc evalue qstart qend sstart send'  -num_descriptions 500 -num_alignments 250 -line_length 60   -out blast_formatter.out
```
which I think is correct too.

The method used to escape strings is very standard:
https://github.com/boutiques/boutiques/blob/d9ffd3ac3e2ca267753a4168660e8e2f2e23a0a6/tools/python/boutiques/localExec.py#L849-L854

How do you suggest this should be modified?

**Comment by ramou** [comment]
Your first example works, but the second command line, while shown by Boutques output, appears not to work. Let me be clear, if you run that command verbatim, things work, but if you actually use bosh, it'll say it uses that command-line, but then it appears that it's not really using it.

I suspect shlex/pipes does escape things properly in the context their used in, I'm not sure that's the whole story because of the bug I experienced. I have confirmed once again that running with the second invocation you show breaks, but running with the third doesn't. However, I think you will find that running with that invocation will give you something like:
```
Error: Too many positional arguments (1), the offending value: qacc
```
which comes from the tool, and which is the error you get when running:
```
/cvmfs/soft.mugqic/CentOS6/software/blast/ncbi-blast-2.7.1+/bin/blast_formatter  -archive out.asn -outfmt 7 qacc sacc evalue qstart qend sstart send       -out blast_formatter.out
```

I'm saying that bosh tells you it's using single quotes around that string, but it looks like it's not actually doing so. I have not hunted for what is causing that, I've just identified the bug.

**Comment by glatard** [comment]
OK, I understand now. Option `-x` in `bosh exec launch` doesn't clean up the shell script run in the container:
```
$ cat temp-1192114762966-1551974423817.localExec.boshjob.sh
#!/bin/sh -l
init_genpipes -a /tmp/$USER/cvmfs-cache -c /etc/parrot/ /cvmfs/soft.mugqic/CentOS6/software/blast/ncbi-blast-2.7.1+/bin/blast_formatter  -archive out.asn -outfmt '7 qacc sacc evalue qstart qend sstart send'  -num_descriptions 500 -num_alignments 250 -line_length 60   -out blast_formatter.out
```
It looks correct to me but there might be a catch there.

**Comment by ramou** [comment]
So here's the fun thing... with -x I get a different result calling the provided shell script directly then when calling it with the command, and sure enough, it's single-quoted in the shell script.

So if boutiques is putting the quotes in place (thanks for pointing out -x), then perhaps it is init_genpipes that is stripping the quote before passing things along. If I can validate this, then it's not boutique's problem and I'll close the ticket (and post one for genpipes)... though I still think the idea of being able to explicitly choose the quoting character would be nice.

**Comment by ramou** [comment]
```

#!/bin/sh -l
echo $@
```
Doing:
```
./foo.sh aslll 'asd asd asd '
```
```
aslll asd asd asd
```
Doing
```
./foo.sh aslll "asd asd asd "
```
```
aslll "asd asd asd "
```

And I can't really report it as a bug because [it can't be fixed](https://stackoverflow.com/questions/54454914/can-i-get-the-original-quote-characters-surrounding-arguments-in-my-bash-script) :\

...this feels vaguely like something I should have known.
