### ISSUE TITLE
Support test invocations outside of the descriptor

### ISSUE THREAD

**Issue by ramou** [boutiques/boutiques#433]
Currently, `bosh test` checks for tests within the descriptor, as per #204. I would like to override this test by passing a second parameter which is just a json object of the tests currently in the descriptor. Extend the arguments a tiny bit:

https://github.com/boutiques/boutiques/blob/5dd403d8e91386469a7bbeab9551170da4917471/tools/python/boutiques/bosh.py#L388-L390
would become
```
    parser.add_argument("descriptor", action="store",
                        help="The Boutiques descriptor as a JSON file, JSON "
                             "string or Zenodo ID (prefixed by 'zenodo.').")
    parser.add_argument("tests", action="store",
                        help="The Boutiques descriptor-styled tests as a JSON file, JSON "
                             "string or Zenodo ID (prefixed by 'zenodo.').")
```
Consistent with my thoughts that we should unify how we take in json.

I'd then suggest that before the call to invocation we convert the descriptor to JSON already, and if `tests` exists, convert that to json too, then just apply it before proceeding as-is.
```
    result.descriptor=loadJson(result.descriptor)
    if results.tests: 
        result.descriptor["tests"]=loadJson(result.tests)
    invocation(result.descriptor)
```

I'd adjust the description to mention that tests overrides the descriptor tests. I'd want to remove tests from the descriptor entirely, but that would suck for backwards compatibility, and I can see the advantage of one-file simple tests (particularly when they don't require special input/output files to do). I'm a fan of overriding instead of merging tests because I'd like to maintain the implied immutability of the descriptors while giving the person who is actually testing control over which tests get run.

**Comment by glatard** [comment]
Hi @ramou, I see some difficulties in separating the tests from the descriptor, in particular related to publication. The motivation for the current design is to allow platforms such as CBRAIN to test that descriptors written externally work properly in their environment. That's why we thought that tests should live within the descriptor. What's the motivation for separating them?

**Comment by ramou** [comment]
The specific motivation is that they serve a separate purpose, just like invocations, which also seem out of place in the descriptor, but are still needed to use a descriptor. Further, complex tests require additional files for the testing which I also feel don't belong directly with the descriptor as they don't benefit someone who just wants to use bosh to run a tool. In thinking about a system to review, validate and describe the status of descriptors under development, the separation of the descriptors from the tests was a solid separation of concerns. Even if I merge the test json back into the descriptor, I still need all the framework around bringing the test files together.

I think that having external platforms validate against tests is worthwhile, but in-lining the tests within the descriptors is not the only way to do that, though perhaps the easiest for specifically that purpose with simpler tests. Further, while my initial inclination is full separation, I acknowledge problems (backwards compatibility being chief for me, but you've indicated other concerns), and thus my proposal is to allow separate tests vs. excluding tests in the descriptor.

What I consider most tests to be is take a simple, fixed (minimal) input file(s) and confirm that when the tool is run, it produces a file with the correct MD5. Currently, the assertions available in the testing are light, but presuming those may eventually grow, this is where I think applicable testing should end up. Incorporating that fully into the descriptor becomes very cumbersome as you need to attach actual files.

I'm wary of the idea of external systems automatically validating discovered things. Including the tests within the descriptor is effectively a short-hand for explicitly telling the service how to do that validation. I would favor an approach that either discovers appropriate tests stored separately (along with any needed files). I'm not sure how CBRAIN registers tools, but if they are entered instead of discovered automatically, then it is simply a matter of adding a tool and then adding a test for that tool separately. 

Skimming CBRAIN, presumably it does/could just use itself to validate, as bosh is a tool and the descriptor and tests (together or separately) are just pieces of data to run the tool on using CBRAIN. In that manner, CBRAIN can use itself to validate whatever new tool is being added before making itself available (presumably the requirement for testing and workflow is something along those lines). In any event, that seems a lot about CBRAIN or any other external tool, and not much about Boutiques.

**Comment by ramou** [comment]
After mulling and discussions, I don't feel as strongly about pushing this. I will switch approaches.
