### ISSUE TITLE
containers limited to docker?

### ISSUE THREAD

**Issue by glatard** [boutiques/boutiques#45]
_From @vsoch on July 12, 2016 21:10_

I noticed in the spec that "docker-image" and "docker-index" are sort of hard coded. They aren't required so having them isn't a big deal, but there doesn't seem to be an appropriate place to specify other kinds of containers. I'm going to use the spec to store basic things about (another kind of) container and then use a different workflow spec (WDL) to actually run things, but I was thinking it would be nice to have this spec move in a direction that would allow for integration with more than Docker. Thanks!

_Copied from original issue: boutiques/tools#22_

**Comment by glatard** [comment]
Thanks for reporting this and for your interest.

About the container format, I don't see any harm in adding other types of tool implementations, containers, VMs, etc. The only issue is that increasing the number of supported implementations will make the tools less portable (e.g. CBRAIN won't support your kind of containers in the short term), but I think we'll have to live with this if this spec is going to be adopted by various platforms. Feel free to add to the spec the (optional) tag(s) that you need for your container type, and to document it in the README. If you think your type of containers is not going to be used outside of your particular context in the short term, you could use a platform-specific tag by prefixing the new tag name with your platform name, e.g. "cbrain:inherits-from-class". If things get complex, we could think of grouping these tags in an "implementation" object.

About linking tools, Boutiques will deliberately stay away from workflow specs. We (you?) could add support for Boutiques in existing workflow languages, they are so many! The only thing that should, in my opinion, be reflected in the spec is that "a workflow is a tool" and "a workflow can submit tasks". We could add a property to cover that, in fact we already have a CBRAIN-specific property (cbrain:can-submit-new-tasks) that we use for that, e.g. to describe PSOM workflows such as in https://github.com/glatard/cbrain-plugins-psom/blob/master/cbrain_task_descriptors/FmriPreprocess.json. This allows to wrap workflow engines in the way (briefly) described in https://ww5.aievolution.com/hbm1601/index.cfm?do=abs.viewAbs&abs=4132 In this way workflows will remain black boxes to the platform, just like any other script.

**Comment by glatard** [comment]
_From @vsoch on July 13, 2016 0:55_

This would be great - for the container format I'll add this as a TODO for singularity containers! For the workflow integration, I'll keep you in the loop for how I think / try out the integration, and I'll definitely take a look at the CBRAIN properties.

**Comment by glatard** [comment]
@vsoch, I just moved this issue as well as #44 from boutiques/tools to here as we're planning to delete the tools repo (it has been merged here). Let me know in case you have any problem with that deletion.

**Comment by glatard** [comment]
See follow-up spec in #58.

**Comment by vsoch** [comment]
awesome, thank you!!
