### ISSUE TITLE
Bosh search doesn't consider all results when ordering by most downloaded

### ISSUE THREAD

**Issue by erinb90** [boutiques/boutiques#450]
By default, `bosh search` will show the top 10 results ordered by "best match". These results will then be reordered by greatest number of downloads. However, this reordering will only be applied to the 10 results originally returned, not of all the results.

For example, `bosh search` currently returns this:
```
ID              TITLE                                   DESCRIPTION                                    DOWNLOADS
zenodo.1451003  qeeg                                    qeeg application                                      21
zenodo.2587157  blast_formatter                         Stand-alone BLAST formatter client, vers...           16
zenodo.2587156  blastdbcheck                            BLAST database integrity and validity ch...           14
zenodo.1450993  PostFreeSurferPipelineBatch-CentOS7     PostFreeSurferPipelineBatch HCP pipeline              10
zenodo.1484547  BIDS App - FreeSurfer 6.0               BIDS App version of freesurfer 6.0, from...           10
zenodo.1450997  FreeSurferPipelineBatch-CentOS7         FreeSurferPipelineBatch HCP pipeline                   9
zenodo.2566455  BIDS App - FSL Diffusion Preprocessing  Preprocessing pipeline for diffusion MRI...            6
zenodo.2566443  mask2boundary                           Transforms a binary mask of a niftii ima...            6
zenodo.2541125  BEst                                    <p>EEG/MEG source localisation technique...            4
zenodo.2566450  BIDS App - ndmg                         ndmg connectome estimation pipeline                    4

```
"Example Boutiques Tool", with 11,571 downloads, is not shown, because it wasn't part of the first 10 results before they were reordered. 

Unfortunately there does not seem to be a way to order by number of downloads when calling Zenodo API. Therefore I see a few possible options:
1. Perform the search in order by "most viewed" instead of "best match". In general, descriptors with a lot of downloads will also have a lot of views, but the results still won't be entirely accurate.
2. Once we know the total number of results, perform the search again, setting `--max` to the total. Reorder all the results by most downloaded, then only display the first 10. This is the most accurate but also the least efficient as it involves an additional API call.
3. Perform the search in order by "most viewed" and display the most viewed instead of the most downloaded. This is simple but changes the requirements of `bosh search`.

**Comment by ramou** [comment]
I spent some time looking at their elasticsearch query support. They use something called [invenio_records_rest](https://github.com/inveniosoftware/invenio-records-rest/tree/master/invenio_records_rest) which uses [elasticsearch_dsl](https://github.com/elastic/elasticsearch-dsl-py) and basically parses a query string. It got opaque to me pretty fast, and I think either a big gulp and sort (still wrong, maybe mix with @erinb90 suggestion of ordering by views and then re-order by downloads) or the solution suggested of changing to order by most viewed. I'm not saying it's impossible with invenio_records_rest, but it doesn't seem reasonable to expend the energy figuring it out.
