### ISSUE TITLE
Separate command-line generation from execution

### ISSUE THREAD

**Issue by glatard** [boutiques/boutiques#455]
The API should be extended with a new function that would return only the command line to be executed in the container. That would allow platforms to use `bosh` for command line generation while keeping control of their execution stack.
@prioux @shots47s

**Comment by erinb90** [comment]
What's the difference between this and `bosh exec simulate`?

**Comment by glatard** [comment]
Indeed that's exactly what `simulate` does:
```
$ bosh exec simulate zenodo.2602109 -i '{"in_file": "file.nii.gz"}'
Generated Command:
mcflirt -in file.nii.gz
```
@prioux @shots47s would it help with `bosh` integration in CBRAIN?

**Comment by glatard** [comment]
Closing this as it seems to be doable through simulate, @prioux, let us know if it should be reopened.
