### ISSUE TITLE
Create a repository for tools exported from Nipype interfaces

### ISSUE THREAD

**Issue by glatard** [boutiques/boutiques#47]
_From @glatard on June 29, 2015 18:12_

_Copied from original issue: glatard/boutiques-applications#1_

**Comment by gkiar** [comment]
Hacktoberfest challenge: Describe a bunch of tools defined in Nipype, in Boutiques, and PR them here into the `examples/` directory (until we decide where to put them more permanently), and add a second PR using `bosh-publish` to the [neurolinks](https://brainhack101.github.io/neurolinks/) project.

**Comment by gkiar** [comment]
@glatard - we push all descriptors to zenodo now, could have tag in descriptors for nipype ones. Close?

**Comment by glatard** [comment]
I guess it would still be useful to export and test interfaces from Nipype.
