### ISSUE TITLE
Use of os.path.realpath

### ISSUE THREAD

**Issue by glatard** [boutiques/boutiques#478]
The code uses `os.path.realpath` instead of `os.path.abspath` in several instances, for instance to mount directories in https://github.com/boutiques/boutiques/blob/master/tools/python/boutiques/localExec.py#L269-L271. This is meant to go around symbolic links and mount the actual (real!) path of directories. However, this may create issues in some cases. @gabiherman, @edickie, would you like to give an example of issues that might be coming from this?

**Comment by gkiar** [comment]
For the record: the use of `realpath` was deliberate because systems like Singularity and Docker don't always mount symbolic locations predictably/consistently across versions.

**Comment by glatard** [comment]
I don't think it should be a problem, but let's see with @gabiherman if it's still an issue when #477 is fixed.

**Comment by gabiherman** [comment]
Sure, this may not be an issue once #477 is fixed. Thanks!
