### ISSUE TITLE
Create a repository for tools available in NITRC

### ISSUE THREAD

**Issue by glatard** [boutiques/boutiques#48]
_From @glatard on June 29, 2015 18:12_

_Copied from original issue: glatard/boutiques-applications#2_

**Comment by gkiar** [comment]
Hacktoberfest challenge: Describe a bunch of NITRC tools in Boutiques, and PR them here into the `examples/` directory (until we decide where to put them more permanently), and add a second PR using `bosh-publish` to the [neurolinks](https://brainhack101.github.io/neurolinks/) project.

**Comment by gkiar** [comment]
@glatard - Same comment as #47  - we push all to zenodo, can optionally add a tag for repo of origin such as nitrc. Close?

**Comment by glatard** [comment]
I don't know, we should look more in NITRC to see if we could export tools automatically from there.
