### ISSUE TITLE
Improve layout of JSON created by 'bosh create'

### ISSUE THREAD

**Issue by prioux** [boutiques/boutiques#480]
I just tried bosh create for the first time, I found the layout of the JSON not that great when I opened it up with an editor. The important fields are all over the place. I would have
like to have at the very top:

    "name": "perlvers", 
    "tool-version": "v9.0.0"
    "command-line": "use English;print \"I am Perl $PERL_VERSION\\n\";", 
    "shell": "/usr/bin/perl",
    "description": "Perl Script Within Boutiques", 

in approximately that order (ignore my values, I'm testing stuff).

Also, there is a spurious blank space after each and every comma.

**Comment by glatard** [comment]
Indeed, the fields are dumpted in alphabetical order, which isn't great. We should fix that in create, maybe in other places too.

**Comment by prioux** [comment]
Related to #520
