### ISSUE TITLE
bosh validate just crashes on bad JSON input

### ISSUE THREAD

**Issue by prioux** [boutiques/boutiques#481]
The bosh validate command just dumps a stack trace with a final message `ValueError: No JSON object could be decoded` when provided with a JSON file with a syntax error. It's really annoying because you can't tell where the error is.

To debug my JSON I loaded it up in the ruby console and got this, which is much more informative:

```
Ruby > f=File.read "a.json";1
 => 1
Ruby > JSON.parse f
JSON::ParserError: 416: unexpected token at '], 
    "schema-version": "0.5", 
    "suggested-resources": {
        "cpu-cores": 1, 
etc etc
```

It told me exactly where the tokenizer crapped out. I had a spurious comma.

**Comment by glatard** [comment]
Yes, we assume that the descriptor is a valid JSON document but we really shouldn't.

**Comment by DarrinFong** [comment]
Is it verbose enough just by using simplejson instead of json?

https://stackoverflow.com/a/14956465
