### ISSUE TITLE
Fixes in pretty print

### ISSUE THREAD

**Issue by glatard** [boutiques/boutiques#491]
1. Mandatory input arguments should be separated from optional ones. For instance, `bosh pprint zenodo.2602109` has `in_file` under optional arguments while it's optional.
2. Output files should be listed last. 
3. Config files should be listed separate from the output files. Config files are output files that have a `file-template` property.

**Comment by DarrinFong** [comment]
> 1. Mandatory input arguments should be separated from optional ones. For instance, `bosh pprint zenodo.2602109` has `in_file` under optional arguments while it's optional.

Do you mean "[...] `in_file` under optional arguments while it's **required**"?

**Comment by glatard** [comment]
Yes, parameter with ID `infile` is under `optional arguments` but I'm not sure why.

**Comment by DarrinFong** [comment]
It's because the optional field of an input is checked but not used to separate the input from others.
It's missing a ```if inp.get("optional"):``` and we need to remove a clk from the optional arguments list if it only contains a non-optional input.

**Comment by DarrinFong** [comment]
Found the answer here https://stackoverflow.com/questions/24180527/argparse-required-arguments-listed-under-optional-arguments

**Comment by DarrinFong** [comment]
@glatard Does your example ```bosh pprint zenodo.260210``` generate config files? If not, can you give an example that would? thanks!

**Comment by glatard** [comment]
`bosh pprint zenodo.3235835` generates config files. The descriptor is a bit complex but we should find a way to display it nicely.
