### ISSUE TITLE
issue with singularity mounting, when mount path contains def_mounts as substring

### ISSUE THREAD

**Issue by jerdra** [boutiques/boutiques#495]
Hi Boutiques devs, 
Just wanted to bring a small issue to your attention:

In <code> localExec.py </code> there's a tidbit where there is definition of paths to exclude from singularity mounting:

<code> def_mounts = ["/proc", "/sys",...] </code>

Later on, exclusions are applied through:

<code>if not any(d in m for d in def_mounts) </code> 

However if a path happens to contain any substring included in <code>def_mounts</code> such as <code>/scratch/project_dir/tmp/test</code>. Then that path is excluded from singularity binding by virtue of having an item from <code>def_mounts</code> as a substring. 

Would it be better to use startswith functionality for exclusion of system directories?

**Comment by glatard** [comment]
Hi @jerdra, thanks for mentioning it! We're removing this logic from the next version, see #488. Does it address your concern?

**Comment by jerdra** [comment]
Great! Looking forward to the release!
