### ISSUE TITLE
Running Docker images in Singularity transparently

### ISSUE THREAD

**Issue by glatard** [boutiques/boutiques#509]
As per #298, we're supposed to run Docker images in Singularity when Docker is not available or when `--force-singularity` is used. This currently doesn't work when Docker images are pulled from DockerHub, which is the main use case. I think that the test in https://github.com/boutiques/boutiques/blob/master/tools/python/boutiques/tests/test_example1.py only works because the tool image is built locally and hence doesn't need to be pulled.

## Expected Behavior

When both Singularity and Docker are installed, the following command lines should all work successfully, assuming that `test.nii.gz` is present in the cwd (see example file [here](https://github.com/boutiques/tutorial/tree/master/notebooks/data)):
```
bosh exec launch zenodo.1482743 '{"infile": "./test.nii.gz", "maskfile": "test_brain.nii.gz"}'
```
```
bosh exec launch --force-singularity zenodo.1482743 '{"infile": "./test.nii.gz", "maskfile": "test_brain.nii.gz"}'
```
## Current Behavior

The command line with `--force-singularity` crashes as follows:
```
h exec launch --force-singularity zenodo.1482743 '{"infile": "./test.nii.gz", "maskfile": "test_brain.nii.gz"}'
docker is /usr/bin/docker
[ ERROR ] Could not pull Singularity image: 
 * Pull command: singularity pull --name "mcin-docker-fsl-latest.simg.tmp" index.docker.io://mcin/docker-fsl:latest
 * Error: FATAL:   Unsupported transport type: index.docker.io
```

This is primarily because `container-image/index` is set to `index.docker.io`. Removing the index entry leads to another error:
```
$ bosh exec launch --force-singularity ~/.cache/boutiques/zenodo-1482743.json '{"infile": "./test.nii.gz", "maskfile": "test_brain.nii.gz"}'
docker is /usr/bin/docker
[ ERROR ] Could not pull Singularity image: 
 * Pull command: singularity pull --name "mcin-docker-fsl-latest.simg.tmp" shub://mcin/docker-fsl:latest
 * Error: FATAL:   Failed to get manifest from Shub: The requested manifest was not found in singularity hub
```
This is because the index defaults to `shub://` when Singularity is used while it should be `docker://` in this case. Setting `container-image/index` to `docker://` solves the issue but it makes the execution break with Docker as `docker://` isn't a valid Docker index (it's a convention adopted by Singularity to specify that an image is stored on DockerHub).

## Possible Solution

When `--force-singularity` is used, default index should be `docker://`. 

This should be fixed here:
https://github.com/boutiques/boutiques/blob/831f937a6b1491af63a800786967e4d9bca1e262/tools/python/boutiques/localExec.py#L400

## Environment

```
$ singularity --version
singularity version 3.2.1-1.fc30
```

```
$ docker --version
Docker version 19.03.0-rc2, build f97efcc806
```

## Steps to Reproduce

See above.

**Comment by DarrinFong** [comment]
I've tried the possible solution and it leads to this error while using ```--force-singularity``` 
```
[ ERROR ] Could not pull Singularity image: 
 * Pull command: singularity pull --name "mcin-docker-fsl-latest.simg.tmp" docker://index.docker.io/mcin/docker-fsl:latest
 * Error: WARNING: pull for Docker Hub is not guaranteed to produce the
WARNING: same image on repeated pull. Use Singularity Registry
WARNING: (shub://) to pull exactly equivalent images.
```
I've also tried different addresses such as ```docker://mcin/docker-fsl:latest```, ```shub://index.docker.io/mcin/docker-fsl:latest```, ```shub://mcin/docker-fsl:latest```, all without being able to execute. Is there a known working uri?

**Comment by glatard** [comment]
You need to add `"index": "docker://"` to the descriptor. Your current error shows that it's still trying to pull from `shub://`.

**Comment by DarrinFong** [comment]
I'm not sure if I understand, by "add" you mean changing the current index in the descriptor to this (json below)? I thought what the descriptor contain can be changed during execution once it's stored in conIndex, or we have to modify the descriptor object itself because it's used some where else?
```
"container-image": {
    "index": "docker://index.docker.io"
}
```
Additionally just running the command ```singularity pull --name "mcin-docker-fsl-latest.simg.tmp" docker://index.docker.io/mcin/docker-fsl:latest``` still yields the same errors but it seems to start importing the image but fails because of some permission error. Maybe the changes work but my file system has some permission issues?
```
WARNING: pull for Docker Hub is not guaranteed to produce the
WARNING: same image on repeated pull. Use Singularity Registry
WARNING: (shub://) to pull exactly equivalent images.
Docker image path: index.docker.io/mcin/docker-fsl:latest
Cache folder set to /home/darrin/.singularity/docker
Importing: base Singularity environment
tar: ./.exec: implausibly old time stamp -9223372036854775808
[...]
Importing: /home/darrin/.singularity/docker/sha256:1378af22889cc46ed54ab588037a2f3f1e03607618dd6e1a388d8b636ef80765.tar.gz
tar: usr/bin/bc: Cannot open: Permission denied
tar: usr/bin/dc: Cannot open: Permission denied
tar: Exiting with failure status due to previous errors
Cleaning up...
```
Thanks for the clarifications

**Comment by glatard** [comment]
`singularity pull --name "mcin-docker-fsl-latest.simg.tmp" docker://index.docker.io/mcin/docker-fsl:latest` works for me, it must be your environment indeed. Sorry this wasn't very clear: the modification should be done in the code indeed, not in the descriptor. It should be fixed here:
https://github.com/boutiques/boutiques/blob/831f937a6b1491af63a800786967e4d9bca1e262/tools/python/boutiques/localExec.py#L400
If image is of type `docker`, then `conIndex` should be set to `docker://` there.

**Comment by glatard** [comment]
I made a quick hack in https://github.com/glatard/boutiques/commit/79b888bf631bffb048dc98810f632c06ffec54bc as I needed this to work today, but this should be more thoroughly tested against various combinations of index (with / without index, index with / without slash at the end, etc).

**Comment by gkiar** [comment]
@glatard to confirm, is this ready for my review, or still a work in progress due to testing, etc.? If still wip, let's add the `[WIP]` designation to the PR title until it's ready for review?

**Comment by glatard** [comment]
This isn't a PR @gkiar, it is still an issue :)

**Comment by gkiar** [comment]
Oops!!!
