### ISSUE TITLE
Invocation schemas

### ISSUE THREAD

**Issue by ttaa9** [boutiques/boutiques#52]
Here are some [examples of invocation schemas](https://github.com/boutiques/boutiques/files/420794/invocationSchemaExamples.zip) for the following tools described with Boutiques:
* FSL bet ([JSON descriptor](https://raw.githubusercontent.com/aces/cbrain-plugins-neuro/dev/cbrain_task_descriptors/fsl_bet.json))
* FSL FAST ([JSON descriptor](https://raw.githubusercontent.com/aces/cbrain-plugins-neuro/dev/cbrain_task_descriptors/fsl_fast.json)) 
* ICA AROMA ([JSON descriptor](https://raw.githubusercontent.com/aces/cbrain-plugins-neuro/dev/cbrain_task_descriptors/ICA-AROMA.json))
* MINC Bet ([JSON descriptor](https://raw.githubusercontent.com/aces/cbrain-plugins-neuro/dev/cbrain_task_descriptors/mincbet.json))

Note that the descriptors are included in the linked zip file above, however. The invocation schemas were manually created, but they can be re-generated using the `invocationSchemaHandler` in https://github.com/boutiques/boutiques/tree/develop/tools.

**Comment by glatard** [comment]
An optional attribute should be added to the tool schema to add invocation schemas.

**Comment by ttaa9** [comment]
You mean something like an `invocation-schema` attribute in the tool descriptor that would contain the entire invocation schema for the inputs of that tool?

**Comment by glatard** [comment]
Yes:
