### ISSUE TITLE
Boutiques publish should not reorder the properties (or have option to keep the original order))

### ISSUE THREAD

**Issue by MontrealSergiy** [boutiques/boutiques#520]
## Purpose
Keep the preferred ordering of arguments to adhere to the principle of the least user astonishment. While the conventional json wisdom is to order a long list of properties alphabetically, some devs, such as Pierre R. rely on handpicked order, say order of importance.

## Context
Zenodo publishing, and perhaps other commands reorder the properties of alphabetically. While ordering might be useful it is not what most users would expect, and obscure the fact that there is actual semantic change (added property).

## Preferred solution (optional)

I suggest to make reordering optional or remove completely 

## Possible Implementation (optional)

there is some param in json.load to keep ordering (in an ordered dictionary)

**Comment by prioux** [comment]
Ah people talk about me behind my back!

Anyway, here's a nice example of a descriptor I hand-crafted with love:

https://github.com/aces/cbrain/commit/2a72a34c29?diff=unified

Knowing me, that thing would also be full of comments if JSON allowed any.
