### ISSUE TITLE
Zenodo API has changed and bosh search is no longer using a valid API

### ISSUE THREAD

**Issue by shots47s** [boutiques/boutiques#528]
It appears that Zenodo has changed their API and no longer supports the endpoint /api/records, it is not /api/deposit/depositions.  They sight that this is to improve performance.

## Expected Behavior

bosh search FSL should return all of the FSL records in zenodo

## Current Behavior
bosh search returns a 500 Error.

## Possible Solution (optional)
Change the API url in searcher.py

## Environment

* 
* 
* 

## Steps to Reproduce

1. bosh search FSL

**Comment by glatard** [comment]
As discussed, the API used by `bosh` (`/api/records`) is still the one to use, but Zenodo is currently experiencing difficulties. `bosh search` is currently working though. Closing this issues as I don't think there is anything for us to fix. Feel free to re-open!
