### ISSUE TITLE
Mounting several mount points 

### ISSUE THREAD

**Issue by prioux** [boutiques/boutiques#540]
Bosh fails to launch a tool in a singularity container when several mount points are asked to be mounted.

The bug was introduced in:

https://github.com/boutiques/boutiques/commit/0873f43f93637ae0de49a6811dee96d051f142fa

Both the original code and the modified code are wrong.

When several mountpoints must be added to the singularity launch command, distinct `-B mountpoint` options must be added to the command line (e.g. `-B abcd -B efgh -B ijkl`).

The original code built `abcd -B efgh -B ijkl` (notice the missing leading `-B`).

The new code builds `-B abcd efgh ijkl` (notice the missing `-B`s for the second and third mountpoints).

**Comment by natacha-beck** [comment]
Closed by https://github.com/boutiques/boutiques/commit/4830d21a57a1ffbe558b8b0a7e0d6603888b41bf

**Comment by prioux** [comment]
Great! I'm 4 months late!
