### ISSUE TITLE
Bug in `get_entry_point` when use `bids import`

### ISSUE THREAD

**Issue by natacha-beck** [boutiques/boutiques#542]
`bosh import bids` failed to retrieve proper entry point according to the following Dockerfile: 
`https://github.com/BIDS-Apps/oppni/blob/master/Dockerfile`

The definition of the ENTRYPOINT is:

 `ENTRYPOINT ["python", "/oppni/oppni.py"]`

note the space between the 2 elems of the ENTRYPOINT definition. It will make the function return  `python",` that is not what it is suppose to be. 
 
## Expected Behavior
In mean time the definition of the ENTRYPOINT seems to be wrong in this Dockerfile according to Docker documentation that specify the following: 

> ENTRYPOINT ["executable", "param1", "param2"]

Then it should be the following:
> ENTRYPOINT ["python /oppni/oppni.py"]

Then my ENTRYPOINT in the Boutiques descriptor became `python` instead of `python  /oppni/oppni.py`  

## Current Behavior
See description at the top.

## Possible Solution (optional)
Refatoring `get_entry_point` to split properly

## Steps to Reproduce
1. git clone https://github.com/BIDS-Apps/oppni
1. bosh import bids oppni.json oppni/

**Comment by natacha-beck** [comment]
Do Boutiques expect to have only `executable` define in ENTRYPOINT or it is possible to get params define in ENTRYPOINT ?

**Comment by gkiar** [comment]
It's possible to get params, as well - in this case, `python` being the executable, `/path/to/oppni` as the second, and whatever args as `2+`. This appears to indeed be a bug in how we're parsing entrypoints, and we should ideally support both formats (i.e. separation by spaces and multiple list items).

You said you have a fix ready to roll in, @natacha-beck
