### ISSUE TITLE
Travis fails Py3.4 job - PyYAML

### ISSUE THREAD

**Issue by DarrinFong** [boutiques/boutiques#571]
Travis-CI fails during Python 3.4 jobs because PyYAML recently (around 06/01/2020) dropped support for Python 3.4.

## Current Behavior

```bash
$ pip install .
Processing /home/travis/build/DarrinFong/boutiques/tools/python
    Complete output from command python setup.py egg_info:
    PyYAML requires Python '>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*' but the running Python is 3.4.6
```

## Possible fix (optional)

Add pyyaml version requirements in setup.py (this doesn't cover py_v between 3 and 3.4, but boutiques doesn't support those versions either)
```python
DEPS = [
  "....",
  "pyyaml==5.2; python_version == '3.4'",
  "pyyaml; python_version != '3.4'"
]
```

**Comment by glatard** [comment]
Sounds good to me!
