### ISSUE TITLE
"estimate" descriptor input fields from config file template

### ISSUE THREAD

**Issue by gkiar** [boutiques/boutiques#575]
## Purpose

Given a configuration file for a tool with default values, generate a base for the descriptor including the inputs and config file template. This would of course just be an estimate because it would be difficult/impossible to identify which strings are just that versus a selection from an enum.

## Context

We have a similar tool for generation of descriptors from argparse and docopt; config files (sticking to the very standardized `.toml`, `.yml`, and `.json` formats) could be similarly handled.

**Comment by glatard** [comment]
We could also generate inputs from a command-line template. This should be added to `bosh create`.

**Comment by DarrinFong** [comment]
Hi @gkiar, my understanding of this is `bosh import [toml | yaml | json | cl_template] [config file]` will create a descriptor, similar to how `bosh import docopt [file]` creates a base descriptor.
The output descriptor will contain `inputs`, and `output-files` (contains a config_file with `file-template`). Is this correct?

Hi @glatard, does it mean `bosh create [output_desc] --cl-template [CL_template]` will populate `inputs` of the `[output_desc]` according to the command-line template?

Thanks for the clarifications!

**Comment by gkiar** [comment]
@DarrinFong exactly on my point, and I'm pretty sure you're also spot on for @glatard 's :)

**Comment by DarrinFong** [comment]
@gkiar I'm having trouble finding config files to test with, do you have some config_file/descriptor that I can validate the generated descriptor against? In case the descriptor for a config file doesn't exist, I can still use the config file to test the import and manually verify the output descriptor. Thanks :)
