### ISSUE TITLE
Support for more containers types

### ISSUE THREAD

**Issue by glatard** [boutiques/boutiques#58]
A tool may contain one and only one of the following attributes:
- Docker index (e.g. `http://index.docker.io`) and image name (e.g. `mcin/ica-aroma:latest`). This is already possible in the schema.
- URL of a rootfs container (e.g. `http://somehwere.org/container-1234.tgz`).
- URL of a singularity container (e.g. `http://somehwere.org/container-singularity-1234.tgz`).

An optional attribute containing the hash of the container may be present. 

A parent `container` object should be created to encapsulate these different implementations.

**Comment by ttaa9** [comment]
Maybe have a `containers` array, which could reference multiple images/containers?

**Comment by glatard** [comment]
No because these implementations must be exclusive: only one can be specified.

**Comment by kofalt** [comment]
SGTM. Since each option might have multiple values, what would you think of something like this?

```js
{
	// ... other boutique values ...

	"input": {
		"type": "docker",
		"index": "http://index.docker.io",
		"image": "mcin/ica-aroma:latest"
	}
}
```

```js
{
	"input": {
		"type": "rootfs",
		"uri": "http://somehwere.org/container-1234.tgz"
	}
}
```

This way, you could use [definitions](https://spacetelescope.github.io/understanding-json-schema/structuring.html#reuse) and the [oneOf](https://spacetelescope.github.io/understanding-json-schema/reference/combining.html#oneof) keyword to formally validate each type.

**Comment by chrisfilo** [comment]
Minor comment: singularity does not yet support .tgz - the images use .img extension

**Comment by vsoch** [comment]
Apologies for being the annoying person to comment on a closed issue - Singularity images support [multiple formats](https://github.com/singularityware/singularity/blob/ac48c7beab7c2b97c71b06e9ad6ab84400ef9dbb/libexec/cli/import.help#L22) and one of them is indeed .tgz. A more complete list of the "weird" ones:

![image](https://cloud.githubusercontent.com/assets/814322/21474861/c21a36c4-cad9-11e6-96e5-84c98332f954.png)
