### ISSUE TITLE
Enum should not be an input type

### ISSUE THREAD

**Issue by johnflavin** [boutiques/boutiques#59]
Rather than having a special input type that allows me to restrict the values of the input to a set, I should be able to restrict the values of _any_ input type to a set. `Enum` should not be an input type, there should be an optional property that any input type can define which will restrict the valid values to a set.

I propose to rename the input property `enum-value-choices` to `value-choices`, and remove the dependency that `enum-value-choices` can only be set for `type=Enum`. (I guess we would also have to remove `items: {type: string}` from `value-choices`? Not sure about that.)

So under this proposed change, an input could be something like 

``` json
{
    "id": "foo",
    "type": "String",
    "value-choices": ["a", "b", "c"]
}
```

Similarly,

``` json
{
    "id": "bar",
    "type": "Number",
    "value-choices": [0, 1, 2]
}
```

should be possible.

**Comment by glatard** [comment]
Yes, I tend to agree with that. @ttaa9?

**Comment by ttaa9** [comment]
Seems reasonable to me. There are cases where I indeed had to put ["1", "2", "3"], although I didn't consider that an issue at the time.
