### ISSUE TITLE
Docker with --gpus option

### ISSUE THREAD

**Issue by gregblt** [boutiques/boutiques#619]
Hello, 

With @fpgdubost we are working on creating Boutiques tools describing his machine learning algorithms. These algorithms require that we use Docker with the "gpus" argument `docker run --gpus all`

We were wondering if there is a way to use this option with Boutiques (bosh exec launch arguments? property in the descriptor?). If not, would it be possible to add this feature to Boutiques? We can help on this if needed

Best,

**Comment by glatard** [comment]
Hi @gregblt, `container-image` has a `container-opts` property that can do this, here is an example:
```
"container-image": {
        "image": "boutiques/example1:test", 
        "index": "docker://",
        "type": "singularity",
        "container-opts": ["--home", "$PWD:$PWD"]
    },
```
Would it work for you?

**Comment by gregblt** [comment]
Yes, perfect! Thank you
