### ISSUE TITLE
Allow localExecutor.py to accept values complying with the schema generated from invocationSchemaHandler.py

### ISSUE THREAD

**Issue by glatard** [boutiques/boutiques#62]

**Comment by ttaa9** [comment]
So, if an invocation schema is specified, it should check input with respect to that only (and not run its own checks)? What does the 'All' mean?

Also, for `absolute-path` and `relative-path`, should localExecutor.py fail if they are not followed (e.g. an input has `absolute-path` given as true but a relative path is given instead)? Or should it silently alter such cases (e.g. if `absolute-path` is given as true, but a relative path is given, should it just alter the given path to conform)?

**Comment by glatard** [comment]
I think the input validation should be done against the input schema whenever inputs are passed in JSON. The input validation schema doesn't have to be passed to the tool, it can be generated on the fly. Actually, it's even better if it's not passed (avoids inconsistencies).

Yes, I think the local executor should fail if `absolute-path` and `relative-path` are not respected. You could add an option to alter as you said.

**Comment by ttaa9** [comment]
Sounds good. I was thinking more in terms of what you mentioned in #52, i.e. when there is an `invocation-schema` attribute specified, it should use it.

**Comment by glatard** [comment]
Yes I guess it should use the invocation schema if there is one. 

The validator could also be extended: if there's an `invocation-schema` and it's wrong, then the descriptor shouldn't validate.

**Comment by ttaa9** [comment]
Shall the localExecutor assume that the invocationSchemaGenerator is in the same directory? I didn't want to copy and paste the invocation schema generation code into the localExecutor (might as well have one script do both jobs then), but I'll have to if we want the scripts to be entirely stand-alone.

Maybe the validator, localExecutor, and invocationSchemaGenerator should all be one script, BoutiquesHelper.py or something.

**Comment by glatard** [comment]
I guess ultimately we could have a library that all the scripts will use when they need it. For now you could assume that all the scripts are accessible through the PATH rather than in the same directory.

**Comment by glatard** [comment]
#141 is a duplicate.
