### ISSUE TITLE
Resource requirements

### ISSUE THREAD

**Issue by glatard** [boutiques/boutiques#63]
It should be possible to add resource requirements for the tool, in particular:
- Amount of RAM required
- Number of CPU cores required
- Amount of disk space required
  Similar to the walltime, it is acknowledged that such estimates are often wrong as they may depend on the data, parameters, etc. But maybe starting with a simple parameter, i.e., Number value, would help in a first step. We just had the issue in CBRAIN that in some clusters all the jobs request 1 12-core node by default; changing this behavior requires manual intervention in the tool configuration, which could be automated by such parameters.

In the future, we may also want to add the following parameters:
- Number of nodes

**Comment by kofalt** [comment]
Agreed!

---

Question: is there truly a use case for *requiring* a certain number of cores? Is there an algorithm such that, if it can't run X concurrent threads, it will fail or take far longer than the reduction in CPU resource would imply?

Maybe this field could be more of an advertisement: "I will use this many cores if you have them."

This also can get hairy with regard to physical / virtual cores. I vote that we leave that distinction ambiguous - if you want to multiplex your VM in a complex scenario you should be able to provide compute to the algorithm however you see fit as a sysadmin.

---

One issue I ran into when thinking about this at Flywheel is that frequently the RAM usage is driven by the data set - we have an algorithm that will consume roughly five times the size of the dicom, IIRC. So it might make sense to set the minimum to 1 GB at one site, but might not work at another site with a different kind of input. And I really don't want to write like `ram: "f(5x)"` in my schema :smile: 

It would also be nice to record that these are suggestions, not hard requirements - and it's acceptable for the algorithm to fail in that case.

**Comment by glatard** [comment]
Yes, I agree that these should be suggestions rather than requirements. We could group these properties in a `suggested-resources` object.
