### ISSUE TITLE
bug in 'example'command 

### ISSUE THREAD

**Issue by mandana-mazaheri** [boutiques/boutiques#639]
The command `bosh example` does not work correctly for some pipelines

## Expected Behavior
 It is expected to generate the invocation template for this pipeline zenodo.1484547

## Current Behavior
 However, it generates a list of ERRORs, this is the error

> 

`$bosh example zenodo.1484547
An error occurred in validation
Previously saved issues
[ ERROR ] ['T2'] is not one of ['T2', 'FLAIR', 'None', 'T1only']

Failed validating 'enum' in schema['properties']['refine_pial']:
    {'enum': ['T2', 'FLAIR', 'None', 'T1only']}

On instance['refine_pial']:
    ['T2']`

## Environment (optional)
 I am working with
python 3.6, 
Docker version 17.05.0-ce, build 89658be
Boutiques 0.5.25

**Comment by gkiar** [comment]
Hi @mandana-mazaheri  - the bug is actually in this descriptor, since the default value for this parameter is improperly specified:

```
{
            "command-line-flag": "--refine_pial",
            "default-value": [
                "T2"
            ],
            "description": "If the dataset contains 3D T2 or T2 FLAIR weighted images (~1x1x1), these can be used to refine the pial surface. If you want to ignore these, specify None or  T1only to base surfaces on the T1 alone.",
            "id": "refine_pial",
            "name": "refine_pial",
            "optional": true,
            "type": "String",
            "value-choices": [
                "T2",
                "FLAIR",
                "None",
                "T1only"
            ],
            "value-key": "[REFINE_PIAL]"
        }
```

If we replace the default value to be the string `"T2"` rather than a list containing that string (which I did in my local cached copy), things work:

```
$ bosh example ~/.cache/boutiques/zenodo-1484547.json
{
    "bids_dir": "str_bids_dir_tW",
    "output_dir": "str_output_dir_Id",
    "analysis_level": "group1",
    "license_file": "str_license_file_lK"
}
```

I know @shots47s wrote this descriptor originally, but am not sure who published it; could've been him, or @glatard?
