### ISSUE TITLE
Have boutiques[minimal] install

### ISSUE THREAD

**Issue by gkiar** [boutiques/boutiques#645]
Boutiques has a growing list of dependencies, and for the basic use case we just want the ability to validate and run a tool. If we use [`setuptools[Extras]`](https://packaging.python.org/tutorials/installing-packages/#id29), we could have a `boutiques[all]` which still gives us everything, but the default would be `boutiques`/`boutiques[minimal]`, which only has this core functionality. Reducing unnecessary dependency clutter, including things like clients for the Zenodo API in cases where execution records and descriptors are managed locally, would lower the barrier to adoption in other platforms.

**Comment by gkiar** [comment]
cc @effigies @adelavega regarding BIDS application specification

**Comment by effigies** [comment]
https://setuptools.readthedocs.io/en/latest/userguide/dependency_management.html#optional-dependencies

**Comment by effigies** [comment]
One thing you can't do is have an extra with fewer dependencies than `install_requires`. There's a discussion [here](https://discuss.python.org/t/adding-a-default-extra-require-environment/4898) about changing that, but it doesn't look like it's going to happen anytime soon. The main alternative is to split out the really core functionality into a minimal `boutiques-core` package, and have the user-friendly `boutiques` depend on that, and still install everything.

**Comment by gkiar** [comment]
Thanks, @effigies. I think we'll make the `install_requires` and base package just be equivalent to the `[minimal]` build (if we even bother adding one, prob don't need it even for clarity). Then the `[all]` and possible others would all be extensions. So we _shouldn't_ have an issue with shrinking our list, I think

**Comment by glatard** [comment]
now available in release 0.5.26
