### ISSUE TITLE
Container hashes

### ISSUE THREAD

**Issue by glatard** [boutiques/boutiques#65]
We haven't specified the hash format that will be used for the container. @kofalt, @gsfr, @chrisfilo:  Any preference?

**Comment by kofalt** [comment]
If we're just talking binary blobs / tarballs, sha384 is fine by me :smile:

**Comment by chrisfilo** [comment]
I'm happy with most options.

**Comment by gsfr** [comment]
flywheel/exchange currently uses sha384.

Sample manifests are [here](https://github.com/flywheel-io/exchange/tree/master/manifests), including hashes and links to hashed artifacts (exported containers).

**Comment by glatard** [comment]
Then sha384 it is!
