### ISSUE TITLE
Handling of file list inputs in local executor

### ISSUE THREAD

**Issue by glatard** [boutiques/boutiques#87]
Options '-r' doesn't generate values for list inputs. Test case in `examples/list` produces the following while a list of files should be added between `list.sh` and `result.txt`:
```
docker run --rm -v $PWD:/work -w /work boutiques/boutiques:develop localExec.py -n 1 -r ./list/list.json
Generated Command:
list.sh  result.txt 
```
It seems to occur only for lists of files. It only occurs when `--dontForcePathType` is not activated.

 It should also be tested with the `-e` option.

**Comment by gkiar** [comment]
Irrelevant with new interface
