### ISSUE TITLE
Questions about documentation

### ISSUE THREAD

**Issue by gkiar** [boutiques/boutiques#92]
Hi,

I am beginning to look at building boutiques containers to wrap my docker pipelines. I have a few comments about the documentation, and places where I would like clarification. Thanks!

- http://boutiques.github.io/
  - [ ] To me, it wasn't immediately obvious where to get started once I read this page? I see examples as json files, and a text editor, but what is the correct first step to take?
- http://boutiques.github.io/json-editor/json-editor.html
  - [ ] I have a docker container, hosted at https://hub.docker.com/r/bids/ndmg/. What is the difference between what this form expects for `docker-index` and `docker-image`?
  - [ ] My docker container has an entrypoint so that the pipeline can be launched immediately on container launch. Does the `command-line` field want a command doing this such as: `docker run -ti -v [localpath]:/data bids/ndmg:v0.0.31-1 [param1] [param2] [param3] [opt1] ...`? Examples such as with [those here](https://github.com/aces/cbrain-plugins-neuro/tree/master/cbrain_task_descriptors) all seem to deal with wrapping commandline functions rather than executable docker containers, so I'm unclear how the direct implementation translates.

That's it for now, thanks!

**Comment by glatard** [comment]
Hi @gkiar,

Thanks for the feedback!

* You're right, we're missing a "Getting started" section. This was reported in #49 already. Currently, the best is to start from existing examples and try to mimic them.
* Your `docker-index` is `http://index.docker.io`. Your Docker image is `bids/ndmg` (possible with a tag appended).
* The command describes the tool independently from Docker. It should be something like "<executable> <param1> <param2> ...". Unfortunately, entry points are currently not supported so you will have to modify your container to remove the entry point.

**Comment by gkiar** [comment]
Great, thanks for the help! I've been able to get past all of the aforementioned hurdles and have now made a modified docker image without an entrypoint, neurodata/ndmg. Here is my current situation:

My pipeline accepts parameters like the following:
```
ndmg_pipeline [DTI] [BVAL] [BVEC] [MPRAGE] [ATLAS] [MASK] [OUTDIR] [LABELS [LABELS]]
```
As you can see, the last parameter,  `[LABELS [LABELS]]`, accepts a list of possible parcellation images. Here, I suggest many options for the user (in fact, I have 24 images packaged with the docker container). The options are thus paths to files on disk, such as `/ndmg_atlases/labels/desikan.nii.gz`. Based on how I understand the schema, and the fact that a) multiple labels can be specified, and b) at least one must be specified, I decided the *groups* category for these parameters made the most sense. This leads to the following questions:

1. is using groups the correct choice?
2. when defining members of the group, and specifying my first member to be `/ndmg_atlases/labels/desikan.nii.gz`, I get an error that I am unsure how to fix, as I did not see a field in which I was required to specify a pattern:
> Value must match the provided pattern
3. if I should not use groups here, then would it make more sense to have this data conveyed as an input of type "list" or "enum"? I suspect enum because I can define and restrict value choices to be image currently within my container?

I apologize for so many questions, and appreciate your support @glatard! Once we get this working I can submit my tool to CBRAIN, and potentially even open a PR adding entrypoint support to the tool.

**Comment by glatard** [comment]
1. No it isn't. What you have is a list where each element must be taken from an enum of strings (not files since these files will stay in the container and not be handled by the framework). We cannot specify restrictions on list elements at the moment. So, the possible solutions are:
   * You specify a list of strings and mention in the documentation that strings have to be taken from a specific list of values.
    * You specify as many string enum inputs as necessary and make them optional. For instance: "first label", "second label", ... "24th label" and only "first label" is not optional (assuming that there must be a label). You could group all these inputs in a group if need be.

PRs are most welcome but this is not an easy one as it has to be implemented both in the Boutiques schema and in the CBRAIN framework.

**Comment by glatard** [comment]
Another comment: once your JSON descriptor is ready, it needs to be put in a "CBRAIN" plugin, i.e. in a directory structure named as follows: <plugin-name>/cbrain_task_descriptors/<task-name>.

See example here: https://github.com/big-data-lab-team/cbrain-plugins-hcp

**Comment by gkiar** [comment]
I see, so a correct command-line format in this schema would actually be:
```
ndmg_pipeline [DTI] [BVAL] [BVEC] [MPRAGE] [ATLAS] [MASK] [OUTDIR] [LABEL1] [LABEL2] ... [LABEL24]
```
Here, each `[LABEL*]` will be an optional enum object with the path to that label stored as the solde option. Then, I can create the "parcellations" group and specify that they are not mutually exclusive but one is required.

@glatard can you confirm this is along the lines of what you meant?

Thanks!

**Comment by glatard** [comment]
Yes but the group doesn't have to have `one-is-required` as long as the first element is not optional. In fact, `one-is-required` would allow to have, say, the 7th element defined while the first 6 are not, which would be at least weird if not incorrect.

**Comment by gkiar** [comment]
Perfect, then I understand.

In the case of this tool, the labels are completely independent of one another, and are literally iterated over in the final stage of the pipeline, thus it does make sense in this context to use `one-is-required` as I do not mind which label file is being used, simply that at least one is.
