### ISSUE TITLE
local exec doesn't seem to pass data into container?

### ISSUE THREAD

**Issue by gkiar** [boutiques/boutiques#94]
Hi,

I am working with an boutiques descriptor located [here](https://github.com/neurodata/boutiques-tools/tree/master). I am trying to run it with the [`localExec.py`](https://github.com/boutiques/boutiques/blob/master/tools/localExec.py) function, but seem to find that the files in my [`input.json`](https://github.com/neurodata/boutiques-tools/blob/master/inputs/ndmg_inputs.json) are not being passed in to the container as I get the following error:

```
python localExec.py -i inputs/ndmg_inputs.json -e cbrain_task_descriptors/ndmg.json
Attempting execution of command:
	ndmg_pipeline  /tmp/project_demo/sub-0025864_session-1_dwi.nii.gz  /tmp/project_demo/sub-0025864_session-1_dwi.bval  /tmp/project_demo/sub-0025864_session-1_dwi.bvec  /tmp/project_demo/sub-0025864_session-1_T1w.nii.gz  /ndmg_atlases/atlas/MNI152_T1_1mm.nii.gz  /ndmg_atlases/atlas/MNI152_T1_1mm_brain_mask.nii.gz  /tmp/project_demo/output/  /ndmg_atlases/labels/desikan.nii.gz    /ndmg_atlases/labels/AAL.nii.gz   -c
---/* Start program output */---
...
IOError: [Errno 2] No such file or directory: '/tmp/project_demo/sub-0025864_session-1_dwi.bvec'
```

When I do `ls` on my local system in that directory, I get the following, verifying that the files do exist in my local system.
```
$ ls /tmp/project_demo
sub-0025864_session-1_T1w.nii.gz	sub-0025864_session-1_dwi.bval		sub-0025864_session-1_dwi.nii.gz
sub-0025864_session-1_bold.nii.gz	sub-0025864_session-1_dwi.bvec
```

Is this expected behaviour? If not, how can I successfully run locally? Thanks!

**Comment by ttaa9** [comment]
Does it work if you put all the data together? I believe the current version of the executor only mounts the $PWD, so it will not have mounted those other folders assuming you're not within them..

**Comment by gkiar** [comment]
Interesting, good to know. That fixed things - thanks for the help! I apologize if I missed that in the documentation somewhere. :)
