### ISSUE TITLE
path-template-stripped-extensions for paths

### ISSUE THREAD

**Issue by gkiar** [boutiques/boutiques#95]
In my descriptor (found [here](https://github.com/neurodata/boutiques-tools/blob/master/cbrain_task_descriptors/ndmg.json)), I am defining several outputs with names relative to the inputs, as is shown below. In this case, I take the input values for `[OUTDIR]` and `[DTI]` into consideration when crafting the path for my new file. However, if the value for `[DTI]` is in anything but the execution directory (say, nested by one level), the produced/desired output filename will not be what is described in the boutiques descriptor, as the entire path to the file is considered in crafting the new filename, though my tool uses just the basename of that file when generating outputs.

Compound with this problem, is that the extension removal does not seem to be functioning properly, either, for reasons unknown to me.

```
{
  "id": "aligned_dti",
  "name": "Aligned DTI volume",
  "path-template": "[OUTDIR]/reg_dti/[DTI]_aligned.nii.gz",
  "path-template-stripped-extensions": [
    "[\".nii\",\".nii.gz\"]"
  ],
  "optional": true
}
```

As an example:
```
[OUTDIR] = /path/to/my/data/derivatives
[DTI] = /path/to/my/data/file.nii.gz
Current value = /path/to/my/data/derivatives/reg_dti/path/to/my/data/file.nii.gz_aligned.nii.gz
Desired value = /path/to/my/data/derivatives/reg_dti/file_aligned.nii.gz
```

As always, thanks for your help!

**Comment by gkiar** [comment]
My current work around has been to make the outputs optional, so then I do get the warning message stating the optional output was not found, but I get no error and the boutique completes its run successfully.

**Comment by ttaa9** [comment]
What happens if you do 
```
 "path-template-stripped-extensions": [
    ".nii", ".nii.gz"
  ],
```
instead?

**Comment by gkiar** [comment]
My file is currently the following, and I get the same two problems
```
{
      "id": "aligned_dti",
      "name": "Aligned DTI volume",
      "path-template": "[OUTDIR]/reg_dti/[DTI]_aligned.nii.gz",
      "path-template-stripped-extensions": [
        ".nii", ".nii.gz"
      ],
      "optional": true
}
```

**Comment by ttaa9** [comment]
Are you using the localExec from the master branch? Try using the one from the development branch [here](https://github.com/boutiques/boutiques/blob/develop/tools/localExec.py).

**Comment by gkiar** [comment]
Running with the dev branch it seems to not pass in my `inputs.json` file; is this expected? It is ignoring my specified inputs and trying to execute the following, verbatim:

```
ndmg_pipeline [DTI] [BVAL] [BVEC] [MPRAGE] [ATLAS] [MASK] [OUTDIR] [DESIKAN] [JHU] [TALAIRACH] [AAL] [HARVARDOXFORD] [CPAC200] [CLEAN]
```

**Comment by gkiar** [comment]
Stepping through the code with `pdb` now suggests that the bug is within `self._generateCmdLineFromInDict()`, as my `self.indict` variable contains expected values, but `self.cmdLine` doesn't reflect these values. I'll PR if I find it before you make the fix 😉

**Comment by gkiar** [comment]
I've made progress here...

with pdb at line 345 it looks good: 
```
(Pdb) print self.in_dict
{u'bvec_file': u'KKI2009_113_1_DTI.bvec', u'bval_file': u'KKI2009_113_1_DTI.bval', u'mask': u'/ndmg_atlases/atlas/MNI152_T1_1mm_brain_mask.nii.gz', u'desikan': u'/ndmg_atlases/labels/desikan.nii.gz', u'dti_file': u'KKI2009_113_1_DTI.nii', u'clean': u'true', u'aal': u'/ndmg_atlases/labels/AAL.nii.gz', u'atlas': u'/ndmg_atlases/atlas/MNI152_T1_1mm.nii.gz', u'mprage_file': u'KKI2009_113_1_MPRAGE.nii', u'outdir': u'output/'}
```
by the time we finish executing line 346 the 4 input files which get passed from outside of the container are all gone:
```
(Pdb) print self.in_dict
{u'bvec_file': '', u'bval_file': '', u'mask': u'/ndmg_atlases/atlas/MNI152_T1_1mm_brain_mask.nii.gz', u'desikan': u'/ndmg_atlases/labels/desikan.nii.gz', u'dti_file': '', u'clean': u'true', u'aal': u'/ndmg_atlases/labels/AAL.nii.gz', u'atlas': u'/ndmg_atlases/atlas/MNI152_T1_1mm.nii.gz', u'mprage_file': '', u'outdir': u'output/'}
```

Digging into `_validateDict` now

**Comment by ttaa9** [comment]
Hi, just wondering if you solved this. I noticed that it seems to work if the inputs are put in a csv now.

**Comment by gkiar** [comment]
Hey there, I got sidetracked so never actually finished this :)
Good to know csv deployment should work - I'll test that next time I'm playing with boutiques and will report back.
