### ISSUE TITLE
Groups that have more than one mandatory inputs cannot have the `mutually-exclusive` property

### ISSUE THREAD

**Issue by pascalgirard** [boutiques/boutiques#98]
Currently, a group can have a one-is-required attribute = true, even if the group gathers only optional inputs.

**Comment by glatard** [comment]
Should be specified in the schema (preferred but tricky) or added to the validator.

**Comment by ttaa9** [comment]
I'm probably totally missing something, but isn't that a useful feature? e.g. in [my ica-aroma descriptor](https://github.com/aces/cbrain-plugins-neuro/blob/master/cbrain_task_descriptors/ICA-AROMA.json).

**Comment by pascalgirard** [comment]
Yes one-is-required attribute is a useful feature. If I understood correctly, the problem is only in the following case : a group with one-is-required = "true" and only optional inputs in the group. By definition optional inputs are not mandatory. The user can fill in none of them. But with one-is-required = "true", he must fill in at least one.

**Comment by glatard** [comment]
@pascalgirard: @ttaa9 is right. It's not a problem if a group only has optional inputs and has the `one-is-required` property. In this case, activating at least one input is correct. 

The problem we were discussing the other day is when a group contains more than one *mandatory* inputs and has the `mutually-exclusive` property. In this case, it is not possible to enter a valid input. 

I just changed the issue title to reflect that. Sorry, I overlooked it when if first looked at it.

**Comment by pascalgirard** [comment]
Ok now I understand the message of ttaa9. And I am sorry to have misunderstood the problem during our last discussion.

**Comment by ttaa9** [comment]
Cool, that makes sense :) The validator [already checks this](https://github.com/boutiques/boutiques/blob/develop/tools/validator.rb) (line 161; unless there's a bug). But I do agree putting it into the schema would be better.

**Comment by glatard** [comment]
Updated #80 and closing this.
